// Shared stock universe for server-side scanning.
// Mirrors the three lists from src/trader.js: stockNames, stockSectors, screenStocks().
// When adding/removing stocks, update BOTH this file and src/trader.js.

const stockNames = {
    // Tech - AI/Software
    'NVDA': 'NVIDIA', 'AMD': 'Advanced Micro Devices', 'GOOGL': 'Alphabet (Google)', 'GOOG': 'Alphabet (Google)',
    'META': 'Meta Platforms', 'PLTR': 'Palantir', 'SNOW': 'Snowflake', 'MSFT': 'Microsoft',
    'ORCL': 'Oracle', 'CRM': 'Salesforce', 'ADBE': 'Adobe', 'NOW': 'ServiceNow',
    'AI': 'C3.ai', 'BBAI': 'BigBear.ai', 'SOUN': 'SoundHound AI', 'PATH': 'UiPath',
    'S': 'SentinelOne', 'HUBS': 'HubSpot', 'ZM': 'Zoom', 'DOCU': 'DocuSign',
    'TEAM': 'Atlassian', 'WDAY': 'Workday', 'VEEV': 'Veeva', 'ESTC': 'Elastic',
    'DDOG': 'Datadog', 'NET': 'Cloudflare', 'MDB': 'MongoDB', 'CRWD': 'CrowdStrike',
    'PANW': 'Palo Alto Networks', 'ZS': 'Zscaler', 'OKTA': 'Okta', 'CFLT': 'Confluent',
    'GTLB': 'GitLab', 'FROG': 'JFrog', 'BILL': 'Bill Holdings', 'DOCN': 'DigitalOcean',
    'MNDY': 'monday.com', 'PCOR': 'Procore', 'APP': 'AppLovin', 'INTU': 'Intuit',
    // Cybersecurity
    'FTNT': 'Fortinet', 'TENB': 'Tenable', 'QLYS': 'Qualys', 'RPD': 'Rapid7', 'VRNS': 'Varonis Systems',
    // Tech - Hardware/Semiconductors
    'AAPL': 'Apple', 'QCOM': 'Qualcomm', 'INTC': 'Intel', 'MU': 'Micron Technology',
    'ARM': 'Arm Holdings', 'AVGO': 'Broadcom', 'TXN': 'Texas Instruments', 'ADI': 'Analog Devices',
    'NXPI': 'NXP Semiconductors', 'KLAC': 'KLA Corporation', 'ASML': 'ASML Holding', 'TSM': 'Taiwan Semiconductor',
    'SNPS': 'Synopsys', 'CDNS': 'Cadence Design', 'ON': 'ON Semiconductor', 'MPWR': 'Monolithic Power',
    'SWKS': 'Skyworks Solutions', 'QRVO': 'Qorvo', 'DELL': 'Dell Technologies', 'HPQ': 'HP Inc.',
    'AMAT': 'Applied Materials', 'LRCX': 'Lam Research', 'MRVL': 'Marvell Technology', 'SMCI': 'Super Micro Computer',
    'ENTG': 'Entegris', 'FORM': 'FormFactor', 'MKSI': 'MKS Instruments', 'COHR': 'Coherent',
    'IPGP': 'IPG Photonics', 'LITE': 'Lumentum', 'AMBA': 'Ambarella', 'SLAB': 'Silicon Labs',
    'CRUS': 'Cirrus Logic', 'SYNA': 'Synaptics', 'MCHP': 'Microchip Technology',
    'WDC': 'Western Digital', 'STX': 'Seagate', 'PSTG': 'Pure Storage', 'NTAP': 'NetApp', 'CHKP': 'Check Point',
    'IONQ': 'IonQ', 'RGTI': 'Rigetti Computing', 'QBTS': 'D-Wave Quantum', 'QUBT': 'Quantum Computing',
    'ARQQ': 'Arqit Quantum', 'IBM': 'IBM', 'WOLF': 'Wolfspeed', 'OUST': 'Ouster',
    'IMOS': 'ChipMOS Technologies', 'VECO': 'Veeco Instruments', 'POWI': 'Power Integrations',
    'PLXS': 'Plexus Corp.', 'VICR': 'Vicor Corporation',
    // EV/Automotive
    'TSLA': 'Tesla', 'RIVN': 'Rivian', 'LCID': 'Lucid Group', 'NIO': 'NIO Inc.',
    'XPEV': 'XPeng', 'LI': 'Li Auto', 'F': 'Ford', 'GM': 'General Motors',
    'STLA': 'Stellantis', 'TM': 'Toyota', 'HMC': 'Honda', 'RACE': 'Ferrari',
    'BLNK': 'Blink Charging', 'CHPT': 'ChargePoint', 'EVGO': 'EVgo', 'PAG': 'Penske Auto',
    'QS': 'QuantumScape', 'ALV': 'Autoliv', 'CVNA': 'Carvana', 'KMX': 'CarMax', 'APTV': 'Aptiv',
    'AN': 'AutoNation', 'LAD': 'Lithia Motors',
    // Finance
    'JPM': 'JPMorgan Chase', 'BAC': 'Bank of America', 'V': 'Visa', 'MA': 'Mastercard',
    'SOFI': 'SoFi', 'PYPL': 'PayPal', 'XYZ': 'Block',
    'WFC': 'Wells Fargo', 'GS': 'Goldman Sachs', 'MS': 'Morgan Stanley', 'C': 'Citigroup',
    'BLK': 'BlackRock', 'SCHW': 'Charles Schwab', 'AFRM': 'Affirm', 'UPST': 'Upstart',
    'NU': 'Nu Holdings', 'MELI': 'MercadoLibre', 'HOOD': 'Robinhood',
    'GPN': 'Global Payments', 'LC': 'LendingClub', 'AXP': 'American Express',
    'FIS': 'Fidelity National', 'COF': 'Capital One', 'ALLY': 'Ally Financial',
    'USB': 'U.S. Bancorp', 'PNC': 'PNC Financial', 'TFC': 'Truist Financial',
    'RF': 'Regions Financial', 'KEY': 'KeyCorp', 'FITB': 'Fifth Third', 'CFG': 'Citizens Financial',
    'HBAN': 'Huntington Bancshares', 'MTB': 'M&T Bank', 'STT': 'State Street', 'BK': 'BNY Mellon',
    'NTRS': 'Northern Trust', 'ZION': 'Zions Bancorp', 'FHN': 'First Horizon',
    'WRB': 'Berkley', 'CB': 'Chubb', 'TRV': 'Travelers', 'ALL': 'Allstate',
    'PGR': 'Progressive', 'AIG': 'AIG', 'MET': 'MetLife', 'PRU': 'Prudential', 'RKT': 'Rocket Companies',
    'FOUR': 'Shift4 Payments', 'PAYO': 'Payoneer', 'DLO': 'DLocal', 'RELY': 'Remitly', 'FLYW': 'Flywire',
    // Growth
    'DKNG': 'DraftKings', 'RBLX': 'Roblox', 'U': 'Unity Software', 'PINS': 'Pinterest',
    'SNAP': 'Snap Inc.', 'SPOT': 'Spotify', 'ROKU': 'Roku', 'ABNB': 'Airbnb',
    'LYFT': 'Lyft', 'DASH': 'DoorDash', 'UBER': 'Uber', 'SHOP': 'Shopify',
    'SE': 'Sea Limited', 'BABA': 'Alibaba', 'JD': 'JD.com', 'PDD': 'PDD Holdings',
    'CPNG': 'Coupang', 'BKNG': 'Booking Holdings', 'EXPE': 'Expedia', 'TCOM': 'Trip.com',
    'TRIP': 'TripAdvisor', 'PTON': 'Peloton', 'OPEN': 'Opendoor', 'COMP': 'Compass Inc.',
    'CWAN': 'Clearwater Analytics', 'DUOL': 'Duolingo', 'BROS': 'Dutch Bros', 'CAVA': 'CAVA Group',
    'TOST': 'Toast', 'GLBE': 'Global-e Online', 'CART': 'Instacart (Maplebear)',
    'GRAB': 'Grab Holdings', 'IOT': 'Samsara', 'BRZE': 'Braze', 'ONON': 'On Holding', 'BIRK': 'Birkenstock',
    // Healthcare
    'JNJ': 'Johnson & Johnson', 'UNH': 'UnitedHealth', 'LLY': 'Eli Lilly', 'PFE': 'Pfizer',
    'MRNA': 'Moderna', 'ABBV': 'AbbVie', 'VRTX': 'Vertex Pharma', 'REGN': 'Regeneron',
    'BMY': 'Bristol Myers Squibb', 'GILD': 'Gilead Sciences', 'AMGN': 'Amgen', 'CVS': 'CVS Health',
    'ISRG': 'Intuitive Surgical', 'TMO': 'Thermo Fisher', 'DHR': 'Danaher', 'ABT': 'Abbott Labs',
    'CI': 'The Cigna Group', 'HUM': 'Humana', 'SYK': 'Stryker', 'BSX': 'Boston Scientific',
    'MDT': 'Medtronic', 'BDX': 'Becton Dickinson', 'BAX': 'Baxter', 'ZBH': 'Zimmer Biomet',
    'HCA': 'HCA Healthcare', 'DVA': 'DaVita',
    'EXAS': 'Exact Sciences', 'ILMN': 'Illumina', 'BIIB': 'Biogen', 'ALNY': 'Alnylam',
    'INCY': 'Incyte', 'NBIX': 'Neurocrine Bio', 'UTHR': 'United Therapeutics', 'JAZZ': 'Jazz Pharma',
    'SRPT': 'Sarepta', 'BMRN': 'BioMarin', 'IONS': 'Ionis Pharma', 'RGEN': 'Repligen',
    'CRSP': 'CRISPR Therapeutics', 'NTLA': 'Intellia Therapeutics', 'BEAM': 'Beam Therapeutics',
    'RXRX': 'Recursion Pharma', 'TWST': 'Twist Bioscience', 'PACB': 'PacBio',
    'EDIT': 'Editas Medicine', 'IOVA': 'Iovance Biotherapeutics', 'PCVX': 'Vaxcyte',
    'MDGL': 'Madrigal Pharma', 'TGTX': 'TG Therapeutics', 'LEGN': 'Legend Biotech',
    'DNA': 'Ginkgo Bioworks', 'FATE': 'Fate Therapeutics',
    'HIMS': 'Hims & Hers', 'DOCS': 'Doximity', 'OSCR': 'Oscar Health',
    // Consumer
    'AMZN': 'Amazon', 'WMT': 'Walmart', 'COST': 'Costco', 'TGT': 'Target',
    'HD': 'Home Depot', 'LOW': "Lowe's", 'SBUX': 'Starbucks', 'MCD': "McDonald's",
    'NKE': 'Nike', 'LULU': 'Lululemon', 'DIS': 'Disney', 'NFLX': 'Netflix',
    'KO': 'Coca-Cola', 'PEP': 'PepsiCo',
    'CMG': 'Chipotle', 'YUM': 'Yum! Brands', 'ETSY': 'Etsy', 'W': 'Wayfair', 'CHWY': 'Chewy',
    'WBD': 'Warner Bros Discovery', 'FOXA': 'Fox Corp', 'CMCSA': 'Comcast',
    'T': 'AT&T', 'VZ': 'Verizon', 'TMUS': 'T-Mobile',
    'PM': 'Philip Morris', 'MO': 'Altria', 'BUD': 'AB InBev', 'TAP': 'Molson Coors',
    'STZ': 'Constellation Brands', 'MNST': 'Monster Beverage', 'CELH': 'Celsius', 'KDP': 'Keurig Dr Pepper',
    'ULTA': 'Ulta Beauty', 'ELF': 'e.l.f. Beauty', 'RH': 'RH (Restoration Hardware)',
    'DECK': 'Deckers Outdoor', 'CROX': 'Crocs', 'LEVI': "Levi Strauss", 'UAA': 'Under Armour',
    'ORLY': "O'Reilly Auto", 'AZO': 'AutoZone', 'AAP': 'Advance Auto Parts',
    'GPC': 'Genuine Parts', 'TSCO': 'Tractor Supply', 'DG': 'Dollar General', 'DLTR': 'Dollar Tree',
    'ROST': 'Ross Stores', 'TJX': 'TJX Companies', 'BBY': 'Best Buy',
    // Energy
    'XOM': 'ExxonMobil', 'CVX': 'Chevron', 'COP': 'ConocoPhillips', 'SLB': 'SLB',
    'NEE': 'NextEra Energy', 'ENPH': 'Enphase', 'FSLR': 'First Solar', 'PLUG': 'Plug Power',
    'EOG': 'EOG Resources', 'OXY': 'Occidental Petroleum', 'MPC': 'Marathon Petroleum', 'PSX': 'Phillips 66',
    'VLO': 'Valero Energy', 'TRGP': 'Targa Resources', 'DVN': 'Devon Energy', 'FANG': 'Diamondback Energy',
    'WMB': 'Williams Companies', 'APA': 'APA Corporation', 'HAL': 'Halliburton', 'BKR': 'Baker Hughes',
    'NOV': 'NOV Inc.', 'FTI': 'TechnipFMC', 'DUK': 'Duke Energy', 'SO': 'Southern Company',
    'D': 'Dominion Energy', 'AEP': 'American Electric Power', 'EXC': 'Exelon', 'OKE': 'ONEOK',
    'SEDG': 'SolarEdge', 'RUN': 'Sunrun', 'PBF': 'PBF Energy', 'DK': 'Delek US',
    'CTRA': 'Coterra Energy', 'OVV': 'Ovintiv', 'PR': 'Permian Resources', 'SM': 'SM Energy',
    'MGY': 'Magnolia Oil', 'MTDR': 'Matador Resources', 'CHRD': 'Chord Energy', 'VNOM': 'Viper Energy',
    'EQT': 'EQT Corporation', 'SMR': 'NuScale Power', 'VST': 'Vistra', 'CEG': 'Constellation Energy',
    'CCJ': 'Cameco', 'LNG': 'Cheniere Energy', 'AR': 'Antero Resources', 'GEV': 'GE Vernova',
    // Industrials
    'BA': 'Boeing', 'CAT': 'Caterpillar', 'DE': 'Deere & Co.', 'GE': 'GE Aerospace',
    'HON': 'Honeywell', 'UPS': 'United Parcel Service', 'FDX': 'FedEx',
    'MMM': '3M', 'UNP': 'Union Pacific', 'NSC': 'Norfolk Southern', 'CSX': 'CSX Corporation',
    'CHRW': 'C.H. Robinson', 'CMI': 'Cummins', 'EMR': 'Emerson Electric', 'ETN': 'Eaton',
    'PH': 'Parker Hannifin', 'ROK': 'Rockwell Automation', 'AME': 'Ametek', 'DOV': 'Dover', 'ITW': 'Illinois Tool Works',
    'DHI': 'D.R. Horton', 'LEN': 'Lennar', 'NVR': 'NVR Inc.', 'PHM': 'PulteGroup',
    'TOL': 'Toll Brothers', 'BLD': 'TopBuild', 'BLDR': 'Builders FirstSource',
    'JBHT': 'J.B. Hunt', 'KNX': 'Knight-Swift', 'ODFL': 'Old Dominion Freight', 'XPO': 'XPO',
    'IR': 'Ingersoll Rand', 'WM': 'WM', 'RSG': 'Republic Services',
    'PCAR': 'Paccar', 'PWR': 'Quanta Services', 'JCI': 'Johnson Controls',
    'AOS': 'A.O. Smith', 'ROP': 'Roper Technologies', 'CARR': 'Carrier Global', 'VLTO': 'Veralto',
    'ROCK': 'Gibraltar Industries', 'MLI': 'Mueller Industries', 'RUSHA': 'Rush Enterprises',
    'MYRG': 'MYR Group', 'DY': 'Dycom Industries', 'APOG': 'Apogee Enterprises',
    'VRT': 'Vertiv Holdings', 'EME': 'EMCOR Group', 'APH': 'Amphenol',
    'HUBB': 'Hubbell', 'WCC': 'WESCO International', 'TT': 'Trane Technologies', 'GNRC': 'Generac Holdings',
    'GEO': 'GEO Group', 'CXW': 'CoreCivic',
    // Real Estate
    'AMT': 'American Tower', 'PLD': 'Prologis', 'EQIX': 'Equinix', 'O': 'Realty Income',
    'CCI': 'Crown Castle', 'PSA': 'Public Storage', 'DLR': 'Digital Realty', 'WELL': 'Welltower',
    'VICI': 'VICI Properties', 'SPG': 'Simon Property', 'AVB': 'AvalonBay', 'EQR': 'Equity Residential',
    'MAA': 'Mid-America Apartment', 'UDR': 'UDR Inc.', 'CPT': 'Camden Property', 'ESS': 'Essex Property',
    'ELS': 'Equity LifeStyle', 'SUI': 'Sun Communities', 'NXRT': 'NexPoint Residential',
    'VTR': 'Ventas', 'STWD': 'Starwood Property', 'DOC': 'Healthpeak', 'OHI': 'Omega Healthcare',
    'SBRA': 'Sabra Healthcare', 'LTC': 'LTC Properties', 'HR': 'Healthcare Realty', 'MPT': 'Medical Properties Trust',
    'NHI': 'National Health Investors', 'CTRE': 'CareTrust REIT', 'IRM': 'Iron Mountain', 'CUBE': 'CubeSmart',
    'NSA': 'National Storage', 'REXR': 'Rexford Industrial',
    'TRNO': 'Terreno Realty', 'SELF': 'Global Self Storage', 'SAFE': 'Safehold',
    // Materials
    'NEM': 'Newmont', 'FCX': 'Freeport-McMoRan', 'NUE': 'Nucor', 'DOW': 'Dow Inc.',
    'USAR': 'USA Rare Earth', 'UUUU': 'Energy Fuels', 'NB': 'NioCorp Developments', 'MP': 'MP Materials',
    'GOLD': 'Barrick Gold', 'AU': 'AngloGold Ashanti', 'AEM': 'Agnico Eagle', 'WPM': 'Wheaton Precious Metals',
    'FNV': 'Franco-Nevada', 'RGLD': 'Royal Gold', 'KGC': 'Kinross Gold', 'HL': 'Hecla Mining',
    'STLD': 'Steel Dynamics', 'RS': 'Reliance Steel', 'CLF': 'Cleveland-Cliffs', 'MT': 'ArcelorMittal',
    'TX': 'Ternium', 'CMC': 'Commercial Metals', 'ATI': 'ATI Inc.',
    'LYB': 'LyondellBasell', 'EMN': 'Eastman Chemical', 'CE': 'Celanese', 'DD': 'DuPont',
    'APD': 'Air Products', 'LIN': 'Linde', 'GTLS': 'Chart Industries', 'NUAI': 'New Era Helium', 'ASPI': 'ASP Isotopes', 'ECL': 'Ecolab',
    'SHW': 'Sherwin-Williams', 'PPG': 'PPG Industries', 'RPM': 'RPM International', 'AXTA': 'Axalta Coating',
    'ALB': 'Albemarle', 'SQM': 'SQM', 'LAC': 'Lithium Americas', 'AA': 'Alcoa',
    'FUL': 'H.B. Fuller', 'NEU': 'NewMarket', 'B': 'Barrick Mining',
    // Defense
    'LMT': 'Lockheed Martin', 'RTX': 'RTX Corporation', 'NOC': 'Northrop Grumman', 'GD': 'General Dynamics',
    'LHX': 'L3Harris', 'HII': 'Huntington Ingalls', 'TXT': 'Textron', 'HWM': 'Howmet Aerospace',
    'AXON': 'Axon Enterprise', 'KTOS': 'Kratos Defense', 'AVAV': 'AeroVironment', 'AIR': 'AAR Corp',
    'SAIC': 'SAIC', 'LDOS': 'Leidos', 'CACI': 'CACI International', 'BAH': 'Booz Allen Hamilton',
    'BWXT': 'BWX Technologies', 'WWD': 'Woodward', 'TDG': 'TransDigm', 'HEI': 'HEICO',
    'CW': 'Curtiss-Wright', 'MOG.A': 'Moog', 'AIN': 'Albany International',
    'PSN': 'Parsons Corporation', 'MRCY': 'Mercury Systems', 'DRS': 'Leonardo DRS',
    'RCAT': 'Red Cat Holdings', 'JOBY': 'Joby Aviation', 'ACHR': 'Archer Aviation',
    // Space
    'RKLB': 'Rocket Lab', 'ASTS': 'AST SpaceMobile', 'LUNR': 'Intuitive Machines',
    'RDW': 'Redwire', 'BKSY': 'BlackSky Technology', 'SPIR': 'Spire Global',
    'IRDM': 'Iridium Communications', 'GSAT': 'Globalstar',
    // Crypto
    'COIN': 'Coinbase', 'MSTR': 'Strategy', 'MARA': 'MARA Holdings',
    'RIOT': 'Riot Platforms', 'CLSK': 'CleanSpark', 'HUT': 'Hut 8',
    'BTDR': 'Bitdeer Technologies', 'BITF': 'Bitfarms',
    // Index Funds
    'SPY': 'S&P 500 ETF', 'QQQ': 'Nasdaq 100 ETF', 'IWM': 'Russell 2000 ETF', 'VOO': 'Vanguard S&P 500'
};

const stockSectors = {
    // Tech - AI/Software
    'NVDA': 'Technology', 'AMD': 'Technology', 'GOOGL': 'Technology', 'GOOG': 'Technology',
    'META': 'Technology', 'PLTR': 'Technology', 'SNOW': 'Technology', 'MSFT': 'Technology',
    'ORCL': 'Technology', 'CRM': 'Technology', 'ADBE': 'Technology', 'NOW': 'Technology',
    'AI': 'Technology', 'BBAI': 'Technology', 'SOUN': 'Technology', 'PATH': 'Technology',
    'S': 'Technology', 'HUBS': 'Technology', 'ZM': 'Technology', 'DOCU': 'Technology',
    'TEAM': 'Technology', 'WDAY': 'Technology', 'VEEV': 'Technology', 'ESTC': 'Technology',
    'DDOG': 'Technology', 'NET': 'Technology', 'MDB': 'Technology', 'CRWD': 'Technology',
    'PANW': 'Technology', 'ZS': 'Technology', 'OKTA': 'Technology', 'CFLT': 'Technology',
    'GTLB': 'Technology', 'FROG': 'Technology', 'BILL': 'Technology', 'DOCN': 'Technology',
    'MNDY': 'Technology', 'PCOR': 'Technology', 'APP': 'Technology', 'INTU': 'Technology',
    'FTNT': 'Technology', 'TENB': 'Technology', 'QLYS': 'Technology', 'RPD': 'Technology', 'VRNS': 'Technology',
    // Tech - Hardware/Semiconductors
    'AAPL': 'Technology', 'QCOM': 'Technology', 'INTC': 'Technology', 'MU': 'Technology',
    'ARM': 'Technology', 'AVGO': 'Technology', 'TXN': 'Technology', 'ADI': 'Technology',
    'NXPI': 'Technology', 'KLAC': 'Technology', 'ASML': 'Technology', 'TSM': 'Technology',
    'SNPS': 'Technology', 'CDNS': 'Technology', 'ON': 'Technology', 'MPWR': 'Technology',
    'SWKS': 'Technology', 'QRVO': 'Technology', 'DELL': 'Technology', 'HPQ': 'Technology',
    'AMAT': 'Technology', 'LRCX': 'Technology', 'MRVL': 'Technology', 'ENTG': 'Technology',
    'FORM': 'Technology', 'MKSI': 'Technology', 'COHR': 'Technology', 'IPGP': 'Technology',
    'LITE': 'Technology', 'AMBA': 'Technology', 'SLAB': 'Technology', 'CRUS': 'Technology',
    'SYNA': 'Technology', 'MCHP': 'Technology', 'SMCI': 'Technology', 'WDC': 'Technology',
    'STX': 'Technology', 'PSTG': 'Technology', 'NTAP': 'Technology', 'CHKP': 'Technology',
    'IONQ': 'Technology', 'RGTI': 'Technology', 'QBTS': 'Technology', 'QUBT': 'Technology',
    'ARQQ': 'Technology', 'IBM': 'Technology', 'WOLF': 'Technology', 'OUST': 'Technology',
    'IMOS': 'Technology', 'VECO': 'Technology', 'POWI': 'Technology', 'PLXS': 'Technology', 'VICR': 'Technology',
    // EV/Automotive
    'TSLA': 'Automotive', 'RIVN': 'Automotive', 'LCID': 'Automotive', 'NIO': 'Automotive',
    'XPEV': 'Automotive', 'LI': 'Automotive', 'F': 'Automotive', 'GM': 'Automotive',
    'STLA': 'Automotive', 'TM': 'Automotive', 'HMC': 'Automotive', 'RACE': 'Automotive',
    'BLNK': 'Automotive', 'CHPT': 'Automotive', 'EVGO': 'Automotive', 'PAG': 'Automotive',
    'QS': 'Automotive', 'ALV': 'Automotive', 'CVNA': 'Automotive', 'KMX': 'Automotive',
    'APTV': 'Automotive', 'AN': 'Automotive', 'LAD': 'Automotive',
    // Finance
    'JPM': 'Financial', 'BAC': 'Financial', 'V': 'Financial', 'MA': 'Financial',
    'SOFI': 'Financial', 'PYPL': 'Financial', 'XYZ': 'Financial', 'GPN': 'Financial',
    'WFC': 'Financial', 'GS': 'Financial', 'MS': 'Financial', 'C': 'Financial',
    'BLK': 'Financial', 'SCHW': 'Financial', 'AFRM': 'Financial', 'UPST': 'Financial',
    'LC': 'Financial', 'NU': 'Financial', 'MELI': 'Financial', 'HOOD': 'Financial',
    'AXP': 'Financial', 'FIS': 'Financial', 'COF': 'Financial', 'ALLY': 'Financial',
    'USB': 'Financial', 'PNC': 'Financial', 'TFC': 'Financial', 'RF': 'Financial',
    'KEY': 'Financial', 'FITB': 'Financial', 'CFG': 'Financial', 'HBAN': 'Financial',
    'MTB': 'Financial', 'STT': 'Financial', 'BK': 'Financial', 'NTRS': 'Financial',
    'ZION': 'Financial', 'FHN': 'Financial',
    'WRB': 'Financial', 'CB': 'Financial', 'TRV': 'Financial', 'ALL': 'Financial',
    'PGR': 'Financial', 'AIG': 'Financial', 'MET': 'Financial', 'PRU': 'Financial',
    'RKT': 'Financial', 'FOUR': 'Financial', 'PAYO': 'Financial', 'DLO': 'Financial',
    'RELY': 'Financial', 'FLYW': 'Financial',
    // Growth Tech/Consumer (mixed sector assignments)
    'DKNG': 'Technology', 'RBLX': 'Technology', 'U': 'Technology', 'PINS': 'Technology',
    'SNAP': 'Technology', 'SPOT': 'Technology', 'ABNB': 'Consumer',
    'LYFT': 'Technology', 'DASH': 'Consumer', 'UBER': 'Technology', 'CPNG': 'Consumer',
    'SHOP': 'Technology', 'SE': 'Consumer', 'BABA': 'Consumer', 'JD': 'Consumer',
    'PDD': 'Consumer', 'BKNG': 'Consumer', 'EXPE': 'Consumer', 'TCOM': 'Consumer', 'TRIP': 'Consumer',
    'PTON': 'Consumer', 'OPEN': 'Technology', 'COMP': 'Technology',
    'CWAN': 'Technology', 'DUOL': 'Technology', 'BROS': 'Consumer', 'CAVA': 'Consumer',
    'TOST': 'Technology', 'GLBE': 'Technology', 'CART': 'Technology',
    'GRAB': 'Technology', 'IOT': 'Technology', 'BRZE': 'Technology',
    'ONON': 'Consumer', 'BIRK': 'Consumer',
    // Healthcare
    'JNJ': 'Healthcare', 'UNH': 'Healthcare', 'LLY': 'Healthcare', 'PFE': 'Healthcare',
    'MRNA': 'Healthcare', 'ABBV': 'Healthcare', 'VRTX': 'Healthcare', 'REGN': 'Healthcare',
    'BMY': 'Healthcare', 'GILD': 'Healthcare', 'AMGN': 'Healthcare', 'CVS': 'Healthcare',
    'CI': 'Healthcare', 'HUM': 'Healthcare', 'ISRG': 'Healthcare', 'TMO': 'Healthcare',
    'DHR': 'Healthcare', 'ABT': 'Healthcare', 'SYK': 'Healthcare', 'BSX': 'Healthcare',
    'MDT': 'Healthcare', 'BDX': 'Healthcare', 'BAX': 'Healthcare', 'ZBH': 'Healthcare',
    'HCA': 'Healthcare', 'DVA': 'Healthcare',
    'EXAS': 'Healthcare', 'ILMN': 'Healthcare', 'BIIB': 'Healthcare', 'ALNY': 'Healthcare',
    'INCY': 'Healthcare', 'NBIX': 'Healthcare', 'UTHR': 'Healthcare', 'JAZZ': 'Healthcare',
    'SRPT': 'Healthcare', 'BMRN': 'Healthcare', 'IONS': 'Healthcare', 'RGEN': 'Healthcare',
    'CRSP': 'Healthcare', 'NTLA': 'Healthcare', 'BEAM': 'Healthcare',
    'RXRX': 'Healthcare', 'TWST': 'Healthcare', 'PACB': 'Healthcare',
    'EDIT': 'Healthcare', 'IOVA': 'Healthcare', 'PCVX': 'Healthcare',
    'MDGL': 'Healthcare', 'TGTX': 'Healthcare', 'LEGN': 'Healthcare',
    'DNA': 'Healthcare', 'FATE': 'Healthcare',
    'HIMS': 'Healthcare', 'DOCS': 'Healthcare', 'OSCR': 'Healthcare',
    // Consumer
    'AMZN': 'Consumer', 'WMT': 'Consumer', 'COST': 'Consumer', 'TGT': 'Consumer',
    'HD': 'Consumer', 'LOW': 'Consumer', 'SBUX': 'Consumer', 'MCD': 'Consumer',
    'CMG': 'Consumer', 'YUM': 'Consumer', 'NKE': 'Consumer', 'LULU': 'Consumer',
    'ETSY': 'Consumer', 'W': 'Consumer', 'CHWY': 'Consumer',
    'DIS': 'Consumer', 'NFLX': 'Consumer', 'ROKU': 'Consumer', 'CARR': 'Industrials', 'WBD': 'Consumer',
    'FOXA': 'Consumer', 'CMCSA': 'Consumer', 'T': 'Consumer', 'VZ': 'Consumer', 'TMUS': 'Consumer',
    'KO': 'Consumer', 'PEP': 'Consumer', 'PM': 'Consumer', 'MO': 'Consumer',
    'BUD': 'Consumer', 'TAP': 'Consumer', 'STZ': 'Consumer', 'MNST': 'Consumer',
    'CELH': 'Consumer', 'KDP': 'Consumer', 'ULTA': 'Consumer', 'ELF': 'Consumer',
    'RH': 'Consumer', 'DECK': 'Consumer', 'CROX': 'Consumer', 'LEVI': 'Consumer',
    'UAA': 'Consumer', 'ORLY': 'Consumer', 'AZO': 'Consumer', 'AAP': 'Consumer',
    'GPC': 'Consumer', 'TSCO': 'Consumer', 'DG': 'Consumer', 'DLTR': 'Consumer',
    'ROST': 'Consumer', 'TJX': 'Consumer', 'BBY': 'Consumer',
    // Energy
    'XOM': 'Energy', 'CVX': 'Energy', 'COP': 'Energy', 'SLB': 'Energy',
    'EOG': 'Energy', 'OXY': 'Energy', 'MPC': 'Energy', 'PSX': 'Energy',
    'VLO': 'Energy', 'TRGP': 'Energy', 'DVN': 'Energy', 'FANG': 'Energy',
    'WMB': 'Energy', 'APA': 'Energy', 'HAL': 'Energy', 'BKR': 'Energy',
    'NOV': 'Energy', 'FTI': 'Energy', 'NEE': 'Energy', 'DUK': 'Energy',
    'SO': 'Energy', 'D': 'Energy', 'AEP': 'Energy', 'EXC': 'Energy', 'OKE': 'Energy',
    'ENPH': 'Energy', 'SEDG': 'Energy', 'RUN': 'Energy',
    'FSLR': 'Energy', 'PLUG': 'Energy', 'PBF': 'Energy', 'DK': 'Energy',
    'CTRA': 'Energy', 'OVV': 'Energy', 'PR': 'Energy', 'SM': 'Energy',
    'MGY': 'Energy', 'MTDR': 'Energy', 'CHRD': 'Energy', 'VNOM': 'Energy',
    'SMR': 'Energy', 'VST': 'Energy', 'CEG': 'Energy', 'CCJ': 'Energy',
    'LNG': 'Energy', 'AR': 'Energy', 'GEV': 'Energy', 'EQT': 'Energy',
    // Industrials
    'BA': 'Industrials', 'CAT': 'Industrials', 'DE': 'Industrials', 'GE': 'Industrials',
    'HON': 'Industrials', 'MMM': 'Industrials', 'UNP': 'Industrials', 'NSC': 'Industrials',
    'CSX': 'Industrials', 'UPS': 'Industrials', 'FDX': 'Industrials', 'CHRW': 'Industrials',
    'CMI': 'Industrials', 'EMR': 'Industrials', 'ETN': 'Industrials', 'PH': 'Industrials',
    'ROK': 'Industrials', 'AME': 'Industrials', 'DOV': 'Industrials', 'ITW': 'Industrials',
    'DHI': 'Industrials', 'LEN': 'Industrials', 'NVR': 'Industrials', 'PHM': 'Industrials',
    'TOL': 'Industrials', 'BLD': 'Industrials', 'BLDR': 'Industrials', 'JBHT': 'Industrials',
    'KNX': 'Industrials', 'ODFL': 'Industrials', 'XPO': 'Industrials',
    'IR': 'Industrials', 'WM': 'Industrials', 'RSG': 'Industrials',
    'PCAR': 'Industrials', 'PWR': 'Industrials', 'JCI': 'Industrials',
    'AOS': 'Industrials', 'ROP': 'Industrials', 'VLTO': 'Industrials',
    'VRT': 'Industrials', 'EME': 'Industrials', 'APH': 'Industrials',
    'HUBB': 'Industrials', 'WCC': 'Industrials', 'TT': 'Industrials', 'GNRC': 'Industrials',
    'GEO': 'Industrials', 'CXW': 'Industrials',
    'ROCK': 'Industrials', 'MLI': 'Industrials', 'RUSHA': 'Industrials',
    'MYRG': 'Industrials', 'DY': 'Industrials', 'APOG': 'Industrials',
    // Real Estate
    'AMT': 'Real Estate', 'PLD': 'Real Estate', 'CCI': 'Real Estate', 'EQIX': 'Real Estate',
    'PSA': 'Real Estate', 'DLR': 'Real Estate', 'WELL': 'Real Estate', 'O': 'Real Estate',
    'VICI': 'Real Estate', 'SPG': 'Real Estate', 'AVB': 'Real Estate', 'EQR': 'Real Estate',
    'MAA': 'Real Estate', 'UDR': 'Real Estate', 'CPT': 'Real Estate', 'ESS': 'Real Estate',
    'ELS': 'Real Estate', 'SUI': 'Real Estate', 'NXRT': 'Real Estate',
    'VTR': 'Real Estate', 'STWD': 'Real Estate', 'DOC': 'Real Estate', 'OHI': 'Real Estate',
    'SBRA': 'Real Estate', 'LTC': 'Real Estate', 'HR': 'Real Estate', 'MPT': 'Real Estate',
    'NHI': 'Real Estate', 'CTRE': 'Real Estate', 'IRM': 'Real Estate', 'CUBE': 'Real Estate',
    'NSA': 'Real Estate', 'REXR': 'Real Estate',
    'TRNO': 'Real Estate', 'SELF': 'Real Estate', 'SAFE': 'Real Estate',
    // Materials
    'NEM': 'Materials', 'FCX': 'Materials', 'GOLD': 'Materials', 'AU': 'Materials',
    'AEM': 'Materials', 'WPM': 'Materials', 'FNV': 'Materials', 'RGLD': 'Materials',
    'KGC': 'Materials', 'HL': 'Materials', 'NUE': 'Materials', 'STLD': 'Materials',
    'RS': 'Materials', 'CLF': 'Materials', 'MT': 'Materials',
    'TX': 'Materials', 'CMC': 'Materials', 'NB': 'Materials', 'ATI': 'Materials',
    'DOW': 'Materials', 'LYB': 'Materials', 'EMN': 'Materials', 'CE': 'Materials',
    'APD': 'Materials', 'LIN': 'Materials', 'GTLS': 'Materials', 'NUAI': 'Materials', 'ASPI': 'Materials', 'ECL': 'Materials',
    'SHW': 'Materials', 'PPG': 'Materials', 'RPM': 'Materials', 'AXTA': 'Materials',
    'ALB': 'Materials', 'SQM': 'Materials', 'LAC': 'Materials', 'AA': 'Materials',
    'MP': 'Materials', 'DD': 'Materials', 'USAR': 'Materials',
    'FUL': 'Materials', 'NEU': 'Materials', 'UUUU': 'Materials', 'B': 'Materials',
    // Defense
    'LMT': 'Defense', 'RTX': 'Defense', 'NOC': 'Defense', 'GD': 'Defense',
    'LHX': 'Defense', 'HII': 'Defense', 'TXT': 'Defense', 'HWM': 'Defense',
    'AXON': 'Defense', 'KTOS': 'Defense', 'AVAV': 'Defense', 'AIR': 'Defense',
    'SAIC': 'Defense', 'LDOS': 'Defense', 'CACI': 'Defense', 'BAH': 'Defense',
    'BWXT': 'Defense', 'WWD': 'Defense', 'MOG.A': 'Defense', 'TDG': 'Defense',
    'HEI': 'Defense', 'CW': 'Defense', 'AIN': 'Defense',
    'PSN': 'Defense', 'MRCY': 'Defense', 'DRS': 'Defense',
    'RCAT': 'Defense', 'JOBY': 'Defense', 'ACHR': 'Defense',
    // Space
    'RKLB': 'Space', 'ASTS': 'Space', 'LUNR': 'Space', 'RDW': 'Space',
    'BKSY': 'Space', 'SPIR': 'Space', 'IRDM': 'Space', 'GSAT': 'Space',
    // Crypto
    'COIN': 'Crypto', 'MSTR': 'Crypto', 'MARA': 'Crypto', 'RIOT': 'Crypto',
    'CLSK': 'Crypto', 'HUT': 'Crypto', 'BTDR': 'Crypto', 'BITF': 'Crypto',
    // Index Funds
    'SPY': 'Index Fund', 'QQQ': 'Index Fund', 'IWM': 'Index Fund', 'VOO': 'Index Fund'
};

// Returns deduplicated list of all scan symbols (matches screenStocks() in trader.js)
function getAllSymbols() {
    const stockLists = {
        techAI: ['NVDA', 'AVGO', 'GOOGL', 'MSFT', 'META', 'ORCL', 'CRM', 'ADBE', 'NOW', 'INTU',
                 'PLTR', 'SNOW', 'AI', 'BBAI', 'SOUN', 'PATH', 'S', 'HUBS', 'ZM', 'DOCU',
                 'TEAM', 'WDAY', 'VEEV', 'ESTC', 'DDOG', 'NET', 'MDB', 'CRWD', 'PANW', 'ZS',
                 'OKTA', 'CFLT', 'GTLB', 'FROG', 'BILL', 'DOCN', 'MNDY', 'PCOR', 'APP',
                 'FTNT', 'TENB', 'QLYS', 'RPD', 'VRNS',
                 'TOST', 'GLBE', 'CART', 'GRAB', 'IOT', 'BRZE'],
        techHardware: ['AAPL', 'QCOM', 'INTC', 'MU', 'ARM', 'DELL', 'HPQ', 'AMAT', 'LRCX', 'MRVL',
                       'AMD', 'TXN', 'ADI', 'NXPI', 'KLAC', 'ASML', 'TSM', 'SNPS', 'CDNS', 'ON',
                       'MPWR', 'SWKS', 'QRVO', 'ENTG', 'FORM', 'MKSI', 'COHR', 'IPGP', 'LITE', 'AMBA',
                       'SLAB', 'CRUS', 'SYNA', 'MCHP', 'SMCI', 'WDC', 'STX', 'PSTG', 'NTAP', 'CHKP',
                       'IONQ', 'RGTI', 'QBTS', 'QUBT', 'ARQQ', 'IBM',
                       'WOLF', 'OUST', 'IMOS', 'VECO', 'POWI', 'PLXS', 'VICR'],
        evAuto: ['TSLA', 'RIVN', 'LCID', 'NIO', 'XPEV', 'LI', 'F', 'GM', 'STLA', 'TM',
                 'HMC', 'RACE', 'APTV', 'ALV', 'BLNK', 'CHPT', 'EVGO', 'PAG', 'QS',
                 'CVNA', 'KMX', 'AN', 'LAD'],
        finance: ['JPM', 'BAC', 'WFC', 'GS', 'MS', 'C', 'BLK', 'SCHW', 'V', 'MA',
                  'XYZ', 'PYPL', 'GPN', 'AXP', 'FIS', 'COF', 'ALLY', 'USB', 'PNC', 'TFC', 'RF',
                  'KEY', 'FITB', 'MTB', 'CFG', 'HBAN', 'STT', 'BK', 'NTRS',
                  'ZION', 'FHN', 'WRB', 'CB', 'TRV', 'ALL', 'PGR', 'AIG', 'MET', 'PRU',
                  'FOUR', 'PAYO', 'DLO', 'RELY', 'FLYW'],
        growth: ['DKNG', 'RBLX', 'U', 'PINS', 'SNAP', 'SPOT', 'ABNB', 'LYFT', 'DASH', 'UBER',
                 'CPNG', 'BKNG', 'EXPE', 'TCOM', 'TRIP', 'PTON', 'LULU', 'ETSY', 'W', 'CHWY',
                 'OPEN', 'COMP', 'RKT', 'CWAN', 'DUOL', 'BROS', 'CAVA', 'HOOD', 'AFRM',
                 'UPST', 'LC', 'NU', 'SOFI', 'NFLX', 'ROKU', 'WBD', 'FOXA', 'CMCSA', 'T',
                 'SHOP', 'SE', 'BABA', 'JD', 'PDD', 'MELI'],
        healthcare: ['JNJ', 'UNH', 'LLY', 'ABBV', 'PFE', 'MRNA', 'VRTX', 'REGN', 'BMY', 'GILD',
                     'AMGN', 'CVS', 'CI', 'HUM', 'ISRG', 'TMO', 'DHR', 'ABT', 'SYK', 'BSX',
                     'MDT', 'BDX', 'BAX', 'ZBH', 'HCA', 'DVA', 'EXAS', 'ILMN',
                     'BIIB', 'ALNY', 'INCY', 'NBIX', 'UTHR', 'JAZZ', 'SRPT', 'BMRN', 'IONS', 'RGEN',
                     'CRSP', 'NTLA', 'BEAM', 'RXRX', 'TWST', 'PACB', 'EDIT', 'IOVA',
                     'PCVX', 'MDGL', 'TGTX', 'LEGN', 'DNA', 'FATE',
                     'HIMS', 'DOCS', 'OSCR'],
        consumer: ['AMZN', 'WMT', 'COST', 'TGT', 'HD', 'LOW', 'SBUX', 'MCD', 'CMG', 'YUM',
                   'NKE', 'RH', 'DECK', 'CROX', 'ULTA', 'ELF', 'LEVI', 'UAA', 'DIS', 'GOOG',
                   'KO', 'PEP', 'PM', 'MO', 'BUD', 'TAP', 'STZ', 'MNST', 'CELH', 'KDP',
                   'ORLY', 'AZO', 'AAP', 'GPC', 'TSCO', 'DG', 'DLTR', 'ROST', 'TJX', 'BBY',
                   'VZ', 'TMUS', 'ONON', 'BIRK'],
        energy: ['XOM', 'CVX', 'COP', 'SLB', 'EOG', 'OXY', 'MPC', 'PSX', 'VLO', 'TRGP',
                 'DVN', 'FANG', 'WMB', 'APA', 'HAL', 'BKR', 'NOV', 'FTI', 'NEE', 'DUK',
                 'SO', 'D', 'AEP', 'EXC', 'ENPH', 'SEDG', 'RUN', 'FSLR', 'PLUG',
                 'PBF', 'DK', 'CTRA', 'OVV', 'PR', 'SM', 'MGY', 'MTDR', 'CHRD', 'OKE',
                 'SMR', 'VST', 'CEG', 'CCJ', 'LNG', 'AR', 'GEV', 'VNOM', 'EQT'],
        industrials: ['CAT', 'DE', 'CMI', 'EMR', 'ETN', 'PH', 'ROK', 'AME', 'DOV', 'ITW',
                      'GE', 'HON', 'MMM', 'DHI', 'LEN', 'NVR', 'PHM', 'TOL', 'BLD', 'BLDR',
                      'UNP', 'NSC', 'CSX', 'UPS', 'FDX', 'CHRW', 'JBHT', 'KNX', 'ODFL', 'XPO',
                      'CARR', 'VLTO', 'IR', 'WM', 'RSG', 'PCAR', 'PWR', 'JCI', 'AOS', 'ROP',
                      'ROCK', 'MLI', 'RUSHA', 'MYRG', 'DY', 'APOG',
                      'VRT', 'EME', 'APH', 'HUBB', 'WCC', 'TT', 'GNRC', 'GEO', 'CXW'],
        realEstate: ['AMT', 'PLD', 'CCI', 'EQIX', 'PSA', 'DLR', 'WELL', 'O', 'VICI', 'SPG',
                     'AVB', 'EQR', 'MAA', 'UDR', 'CPT', 'ESS', 'ELS', 'SUI', 'NXRT',
                     'VTR', 'STWD', 'DOC', 'OHI', 'SBRA', 'LTC', 'HR', 'MPT', 'NHI', 'CTRE',
                     'IRM', 'CUBE', 'NSA', 'REXR', 'TRNO', 'SELF', 'SAFE'],
        materials: ['NEM', 'FCX', 'GOLD', 'AU', 'AEM', 'WPM', 'FNV', 'RGLD', 'KGC', 'HL',
                    'NUE', 'STLD', 'RS', 'CLF', 'AA', 'MT', 'TX', 'CMC', 'NB', 'ATI',
                    'DOW', 'LYB', 'EMN', 'CE', 'APD', 'LIN', 'GTLS', 'NUAI', 'ASPI', 'ECL', 'ALB', 'SQM', 'LAC',
                    'MP', 'DD', 'PPG', 'SHW', 'RPM', 'AXTA', 'FUL', 'NEU', 'USAR', 'UUUU', 'B'],
        defense: ['LMT', 'RTX', 'NOC', 'GD', 'BA', 'LHX', 'HII', 'TXT', 'HWM', 'AXON',
                  'KTOS', 'AVAV', 'AIR', 'SAIC', 'LDOS', 'CACI', 'BAH', 'BWXT', 'WWD', 'MOG.A',
                  'TDG', 'HEI', 'CW', 'AIN', 'PSN', 'MRCY', 'DRS',
                  'RCAT', 'JOBY', 'ACHR'],
        space: ['RKLB', 'ASTS', 'LUNR', 'RDW', 'BKSY', 'SPIR', 'IRDM', 'GSAT'],
        crypto: ['COIN', 'MSTR', 'MARA', 'RIOT', 'CLSK', 'HUT', 'BTDR', 'BITF']
    };

    const all = [];
    for (const stocks of Object.values(stockLists)) {
        all.push(...stocks);
    }
    // Deduplicate (some stocks appear in multiple lists, e.g. GOOG in consumer + tech)
    return [...new Set(all)];
}

module.exports = { stockNames, stockSectors, getAllSymbols };
