// Shared stock universe for server-side scanning.
// Mirrors the three lists from src/trader.js: stockNames, stockSectors, screenStocks().
// When adding/removing stocks, update BOTH this file and src/trader.js.

const stockNames = {
    // Tech - AI/Software
    'NVDA': 'NVIDIA', 'AMD': 'Advanced Micro Devices', 'GOOGL': 'Alphabet (Google)', 'GOOG': 'Alphabet (Google)',
    'META': 'Meta Platforms', 'PLTR': 'Palantir', 'SNOW': 'Snowflake', 'MSFT': 'Microsoft',
    'ORCL': 'Oracle', 'CRM': 'Salesforce', 'ADBE': 'Adobe', 'NOW': 'ServiceNow',
    'AI': 'C3.ai', 'BBAI': 'BigBear.ai', 'SOUN': 'SoundHound AI', 'PATH': 'UiPath',
    'S': 'SentinelOne', 'HUBS': 'HubSpot', 'ZM': 'Zoom', 'DOCU': 'DocuSign',
    'TEAM': 'Atlassian', 'WDAY': 'Workday', 'VEEV': 'Veeva', 'ESTC': 'Elastic',
    'DDOG': 'Datadog', 'NET': 'Cloudflare', 'MDB': 'MongoDB', 'CRWD': 'CrowdStrike',
    'PANW': 'Palo Alto Networks', 'ZS': 'Zscaler', 'OKTA': 'Okta', 'CFLT': 'Confluent',
    'GTLB': 'GitLab', 'FROG': 'JFrog', 'BILL': 'Bill Holdings', 'DOCN': 'DigitalOcean',
    'MNDY': 'monday.com', 'PCOR': 'Procore', 'APP': 'AppLovin', 'INTU': 'Intuit',
    // Cybersecurity
    'FTNT': 'Fortinet', 'TENB': 'Tenable', 'QLYS': 'Qualys', 'RPD': 'Rapid7', 'VRNS': 'Varonis Systems',
    // S&P 500 Technology additions
    'ACN': 'Accenture', 'ADSK': 'Autodesk', 'ANET': 'Arista Networks', 'CSCO': 'Cisco',
    'CTSH': 'Cognizant', 'EPAM': 'EPAM Systems', 'FFIV': 'F5 Networks', 'FICO': 'Fair Isaac',
    'GDDY': 'GoDaddy', 'GEN': 'Gen Digital', 'GLW': 'Corning', 'HPE': 'HP Enterprise',
    'JBL': 'Jabil', 'KEYS': 'Keysight Technologies', 'MSI': 'Motorola Solutions',
    'PAYC': 'Paycom', 'PTC': 'PTC Inc.', 'TEL': 'TE Connectivity', 'TER': 'Teradyne',
    'TRMB': 'Trimble', 'TTD': 'Trade Desk', 'TYL': 'Tyler Technologies',
    'VRSN': 'VeriSign', 'ZBRA': 'Zebra Technologies', 'CDW': 'CDW Corp.',
    'AKAM': 'Akamai', 'CIEN': 'Ciena', 'CSGP': 'CoStar Group', 'NDSN': 'Nordson',
    'TDY': 'Teledyne Technologies',
    'GRMN': 'Garmin', 'IT': 'Gartner', 'CHTR': 'Charter Communications',
    // Technology - Gaming/Media
    'EA': 'Electronic Arts', 'TTWO': 'Take-Two Interactive', 'FOX': 'Fox Corp Class B',
    'MTCH': 'Match Group',
    // Mid-cap Technology additions
    'CRDO': 'Credo Technology', 'RMBS': 'Rambus', 'LSCC': 'Lattice Semiconductor',
    'MTSI': 'MACOM Technology', 'DIOD': 'Diodes Inc.', 'NTNX': 'Nutanix',
    'ASAN': 'Asana', 'FIVN': 'Five9', 'RBRK': 'Rubrik',
    'GTM': 'ZoomInfo', 'DT': 'Dynatrace',
    'TWLO': 'Twilio', 'DBX': 'Dropbox', 'BOX': 'Box Inc.',
    'YOU': 'Clear Secure', 'SMTC': 'Semtech', 'CALX': 'Calix', 'PI': 'Impinj',
    'MANH': 'Manhattan Associates', 'GWRE': 'Guidewire', 'WK': 'Workiva',
    'BSY': 'Bentley Systems', 'APPF': 'AppFolio', 'PCTY': 'Paylocity',
    // Tech - Hardware/Semiconductors
    'AAPL': 'Apple', 'QCOM': 'Qualcomm', 'INTC': 'Intel', 'MU': 'Micron Technology',
    'ARM': 'Arm Holdings', 'AVGO': 'Broadcom', 'TXN': 'Texas Instruments', 'ADI': 'Analog Devices',
    'NXPI': 'NXP Semiconductors', 'KLAC': 'KLA Corporation', 'ASML': 'ASML Holding', 'TSM': 'Taiwan Semiconductor',
    'SNPS': 'Synopsys', 'CDNS': 'Cadence Design', 'ON': 'ON Semiconductor', 'MPWR': 'Monolithic Power',
    'SWKS': 'Skyworks Solutions', 'QRVO': 'Qorvo', 'DELL': 'Dell Technologies', 'HPQ': 'HP Inc.',
    'AMAT': 'Applied Materials', 'LRCX': 'Lam Research', 'MRVL': 'Marvell Technology', 'SMCI': 'Super Micro Computer',
    'ENTG': 'Entegris', 'FORM': 'FormFactor', 'MKSI': 'MKS Instruments', 'COHR': 'Coherent',
    'IPGP': 'IPG Photonics', 'LITE': 'Lumentum', 'AMBA': 'Ambarella', 'SLAB': 'Silicon Labs',
    'CRUS': 'Cirrus Logic', 'SYNA': 'Synaptics', 'MCHP': 'Microchip Technology',
    'WDC': 'Western Digital', 'STX': 'Seagate', 'PSTG': 'Pure Storage', 'NTAP': 'NetApp', 'CHKP': 'Check Point',
    'IONQ': 'IonQ', 'RGTI': 'Rigetti Computing', 'QBTS': 'D-Wave Quantum', 'QUBT': 'Quantum Computing',
    'ARQQ': 'Arqit Quantum', 'IBM': 'IBM', 'WOLF': 'Wolfspeed', 'OUST': 'Ouster',
    'IMOS': 'ChipMOS Technologies', 'VECO': 'Veeco Instruments', 'POWI': 'Power Integrations',
    'PLXS': 'Plexus Corp.', 'VICR': 'Vicor Corporation',
    // EV/Automotive
    'TSLA': 'Tesla', 'RIVN': 'Rivian', 'LCID': 'Lucid Group', 'NIO': 'NIO Inc.',
    'XPEV': 'XPeng', 'LI': 'Li Auto', 'F': 'Ford', 'GM': 'General Motors',
    'STLA': 'Stellantis', 'TM': 'Toyota', 'HMC': 'Honda', 'RACE': 'Ferrari',
    'BLNK': 'Blink Charging', 'CHPT': 'ChargePoint', 'EVGO': 'EVgo', 'PAG': 'Penske Auto',
    'QS': 'QuantumScape', 'ALV': 'Autoliv', 'CVNA': 'Carvana', 'KMX': 'CarMax', 'APTV': 'Aptiv',
    'AN': 'AutoNation', 'LAD': 'Lithia Motors',
    // Finance
    'JPM': 'JPMorgan Chase', 'BAC': 'Bank of America', 'V': 'Visa', 'MA': 'Mastercard',
    'SOFI': 'SoFi', 'PYPL': 'PayPal', 'XYZ': 'Block',
    'WFC': 'Wells Fargo', 'GS': 'Goldman Sachs', 'MS': 'Morgan Stanley', 'C': 'Citigroup',
    'BLK': 'BlackRock', 'SCHW': 'Charles Schwab', 'AFRM': 'Affirm', 'UPST': 'Upstart',
    'NU': 'Nu Holdings', 'MELI': 'MercadoLibre', 'HOOD': 'Robinhood',
    'GPN': 'Global Payments', 'LC': 'LendingClub', 'AXP': 'American Express',
    'FIS': 'Fidelity National', 'COF': 'Capital One', 'ALLY': 'Ally Financial',
    'USB': 'U.S. Bancorp', 'PNC': 'PNC Financial', 'TFC': 'Truist Financial',
    'RF': 'Regions Financial', 'KEY': 'KeyCorp', 'FITB': 'Fifth Third', 'CFG': 'Citizens Financial',
    'HBAN': 'Huntington Bancshares', 'MTB': 'M&T Bank', 'STT': 'State Street', 'BK': 'BNY Mellon',
    'NTRS': 'Northern Trust', 'ZION': 'Zions Bancorp', 'FHN': 'First Horizon',
    'WRB': 'Berkley', 'CB': 'Chubb', 'TRV': 'Travelers', 'ALL': 'Allstate',
    'PGR': 'Progressive', 'AIG': 'AIG', 'MET': 'MetLife', 'PRU': 'Prudential', 'RKT': 'Rocket Companies',
    'FOUR': 'Shift4 Payments', 'PAYO': 'Payoneer', 'DLO': 'DLocal', 'RELY': 'Remitly', 'FLYW': 'Flywire',
    // S&P 500 Financial additions
    'SPGI': 'S&P Global', 'ICE': 'Intercontinental Exchange', 'CME': 'CME Group',
    'MCO': "Moody's", 'MSCI': 'MSCI Inc.', 'NDAQ': 'Nasdaq Inc.',
    'AON': 'Aon', 'AJG': 'Arthur J. Gallagher', 'ACGL': 'Arch Capital',
    'AFL': 'Aflac', 'CINF': 'Cincinnati Financial', 'BRO': 'Brown & Brown',
    'GL': 'Globe Life', 'ERIE': 'Erie Indemnity', 'EG': 'Everest Group',
    'BRK.B': 'Berkshire Hathaway', 'BX': 'Blackstone', 'KKR': 'KKR & Co.',
    'APO': 'Apollo Global', 'ARES': 'Ares Management', 'IBKR': 'Interactive Brokers',
    'PFG': 'Principal Financial', 'L': 'Loews', 'BEN': 'Franklin Templeton',
    'IVZ': 'Invesco', 'SYF': 'Synchrony Financial', 'CBOE': 'Cboe Global Markets',
    'RJF': 'Raymond James', 'AMP': 'Ameriprise', 'TROW': 'T. Rowe Price',
    'FISV': 'Fiserv', 'HIG': 'Hartford Financial', 'CPAY': 'Corpay', 'AIZ': 'Assurant', 'JKHY': 'Jack Henry & Associates',
    'CBRE': 'CBRE Group', 'FDS': 'FactSet Research', 'VRSK': 'Verisk Analytics',
    'WTW': 'Willis Towers Watson', 'EFX': 'Equifax',
    // Mid-cap Financial additions
    'WAL': 'Western Alliance', 'EWBC': 'East West Bancshares',
    'FNB': 'F.N.B. Corp.', 'WTFC': 'Wintrust', 'PNFP': 'Pinnacle Financial',
    'SSB': 'SouthState', 'BOKF': 'BOK Financial', 'GBCI': 'Glacier Bancorp',
    'FLG': 'Flagstar Financial', 'OZK': 'Bank OZK',
    'SBCF': 'Seacoast Banking', 'UMBF': 'UMB Financial',
    'FCNCA': 'First Citizens Bancshares', 'FNF': 'Fidelity National Financial',
    'FAF': 'First American Financial', 'ESNT': 'Essent Group',
    'RDN': 'Radian Group', 'KNSL': 'Kinsale Capital', 'RLI': 'RLI Corp.',
    'ORI': 'Old Republic', 'THG': 'Hanover Insurance',
    'AFG': 'American Financial Group', 'RYAN': 'Ryan Specialty',
    'JEF': 'Jefferies', 'EVR': 'Evercore', 'PJT': 'PJT Partners',
    'HLI': 'Houlihan Lokey', 'LPLA': 'LPL Financial', 'PIPR': 'Piper Sandler',
    'SF': 'Stifel Financial', 'MKTX': 'MarketAxess', 'VIRT': 'Virtu Financial',
    'TW': 'Tradeweb Markets',
    // Growth
    'DKNG': 'DraftKings', 'RBLX': 'Roblox', 'U': 'Unity Software', 'PINS': 'Pinterest',
    'SNAP': 'Snap Inc.', 'SPOT': 'Spotify', 'ROKU': 'Roku', 'ABNB': 'Airbnb',
    'LYFT': 'Lyft', 'DASH': 'DoorDash', 'UBER': 'Uber', 'SHOP': 'Shopify',
    'SE': 'Sea Limited', 'BABA': 'Alibaba', 'JD': 'JD.com', 'PDD': 'PDD Holdings',
    'CPNG': 'Coupang', 'BKNG': 'Booking Holdings', 'EXPE': 'Expedia', 'TCOM': 'Trip.com',
    'TRIP': 'TripAdvisor', 'PTON': 'Peloton', 'OPEN': 'Opendoor', 'COMP': 'Compass Inc.',
    'CWAN': 'Clearwater Analytics', 'DUOL': 'Duolingo', 'BROS': 'Dutch Bros', 'CAVA': 'CAVA Group',
    'TOST': 'Toast', 'GLBE': 'Global-e Online', 'CART': 'Instacart (Maplebear)',
    'GRAB': 'Grab Holdings', 'IOT': 'Samsara', 'BRZE': 'Braze', 'ONON': 'On Holding', 'BIRK': 'Birkenstock',
    // Healthcare
    'JNJ': 'Johnson & Johnson', 'UNH': 'UnitedHealth', 'LLY': 'Eli Lilly', 'PFE': 'Pfizer',
    'MRNA': 'Moderna', 'ABBV': 'AbbVie', 'VRTX': 'Vertex Pharma', 'REGN': 'Regeneron',
    'BMY': 'Bristol Myers Squibb', 'GILD': 'Gilead Sciences', 'AMGN': 'Amgen', 'CVS': 'CVS Health',
    'ISRG': 'Intuitive Surgical', 'TMO': 'Thermo Fisher', 'DHR': 'Danaher', 'ABT': 'Abbott Labs',
    'CI': 'The Cigna Group', 'HUM': 'Humana', 'SYK': 'Stryker', 'BSX': 'Boston Scientific',
    'MDT': 'Medtronic', 'BDX': 'Becton Dickinson', 'BAX': 'Baxter', 'ZBH': 'Zimmer Biomet',
    'HCA': 'HCA Healthcare', 'DVA': 'DaVita',
    'EXAS': 'Exact Sciences', 'ILMN': 'Illumina', 'BIIB': 'Biogen', 'ALNY': 'Alnylam',
    'INCY': 'Incyte', 'NBIX': 'Neurocrine Bio', 'UTHR': 'United Therapeutics', 'JAZZ': 'Jazz Pharma',
    'SRPT': 'Sarepta', 'BMRN': 'BioMarin', 'IONS': 'Ionis Pharma', 'RGEN': 'Repligen',
    'CRSP': 'CRISPR Therapeutics', 'NTLA': 'Intellia Therapeutics', 'BEAM': 'Beam Therapeutics',
    'RXRX': 'Recursion Pharma', 'TWST': 'Twist Bioscience', 'PACB': 'PacBio',
    'EDIT': 'Editas Medicine', 'IOVA': 'Iovance Biotherapeutics', 'PCVX': 'Vaxcyte',
    'MDGL': 'Madrigal Pharma', 'TGTX': 'TG Therapeutics', 'LEGN': 'Legend Biotech',
    'DNA': 'Ginkgo Bioworks', 'FATE': 'Fate Therapeutics',
    'HIMS': 'Hims & Hers', 'DOCS': 'Doximity', 'OSCR': 'Oscar Health',
    'ZTS': 'Zoetis', 'WAT': 'Waters Corp.',
    // S&P 500 Healthcare additions
    'MRK': 'Merck', 'A': 'Agilent Technologies', 'IQV': 'IQVIA',
    'GEHC': 'GE HealthCare', 'HOLX': 'Hologic', 'DXCM': 'DexCom',
    'IDXX': 'IDEXX Labs', 'PODD': 'Insulet', 'ALGN': 'Align Technology',
    'EW': 'Edwards Lifesciences', 'COO': 'CooperCompanies',
    'MTD': 'Mettler-Toledo', 'WST': 'West Pharma', 'TECH': 'Bio-Techne',
    'CNC': 'Centene', 'MOH': 'Molina Healthcare', 'COR': 'Cencora',
    'CAH': 'Cardinal Health', 'MCK': 'McKesson', 'VTRS': 'Viatris',
    'LH': 'LabCorp', 'DGX': 'Quest Diagnostics', 'RMD': 'ResMed',
    'ELV': 'Elevance Health', 'STE': 'Steris', 'HSIC': 'Henry Schein',
    'UHS': 'Universal Health', 'CRL': 'Charles River Labs', 'RVTY': 'Revvity',
    'SOLV': 'Solventum',
    // Mid-cap Healthcare additions
    'NVCR': 'NovoCure', 'GKOS': 'Glaukos', 'NVST': 'Envista',
    'XRAY': 'Dentsply Sirona', 'TFX': 'Teleflex', 'MMSI': 'Merit Medical',
    'PEN': 'Penumbra', 'LNTH': 'Lantheus', 'AZTA': 'Azenta',
    'NEOG': 'Neogen', 'PRCT': 'PROCEPT BioRobotics', 'IRTC': 'iRhythm',
    'HALO': 'Halozyme', 'INSM': 'Insmed', 'RARE': 'Ultragenyx',
    'PTCT': 'PTC Therapeutics', 'ARWR': 'Arrowhead Pharma',
    'FOLD': 'Amicus Therapeutics', 'MYGN': 'Myriad Genetics',
    'GH': 'Guardant Health', 'NTRA': 'Natera', 'SDGR': 'Schrodinger',
    'VERA': 'Vera Therapeutics',
    // Consumer
    'AMZN': 'Amazon', 'WMT': 'Walmart', 'COST': 'Costco', 'TGT': 'Target',
    'HD': 'Home Depot', 'LOW': "Lowe's", 'SBUX': 'Starbucks', 'MCD': "McDonald's",
    'NKE': 'Nike', 'LULU': 'Lululemon', 'DIS': 'Disney', 'NFLX': 'Netflix',
    'KO': 'Coca-Cola', 'PEP': 'PepsiCo',
    'CMG': 'Chipotle', 'YUM': 'Yum! Brands', 'ETSY': 'Etsy', 'W': 'Wayfair', 'CHWY': 'Chewy',
    'WBD': 'Warner Bros Discovery', 'FOXA': 'Fox Corp', 'CMCSA': 'Comcast',
    'OMC': 'Omnicom Group',
    'T': 'AT&T', 'VZ': 'Verizon', 'TMUS': 'T-Mobile',
    'PM': 'Philip Morris', 'MO': 'Altria', 'BUD': 'AB InBev', 'TAP': 'Molson Coors',
    'STZ': 'Constellation Brands', 'MNST': 'Monster Beverage', 'CELH': 'Celsius', 'KDP': 'Keurig Dr Pepper',
    'ULTA': 'Ulta Beauty', 'ELF': 'e.l.f. Beauty', 'RH': 'RH (Restoration Hardware)',
    'DECK': 'Deckers Outdoor', 'CROX': 'Crocs', 'LEVI': "Levi Strauss", 'UAA': 'Under Armour',
    'ORLY': "O'Reilly Auto", 'AZO': 'AutoZone', 'AAP': 'Advance Auto Parts',
    'GPC': 'Genuine Parts', 'TSCO': 'Tractor Supply', 'DG': 'Dollar General', 'DLTR': 'Dollar Tree',
    'ROST': 'Ross Stores', 'TJX': 'TJX Companies', 'BBY': 'Best Buy',
    // S&P 500 Consumer additions
    'PG': 'Procter & Gamble', 'CL': 'Colgate-Palmolive', 'KHC': 'Kraft Heinz',
    'MDLZ': 'Mondelez', 'GIS': 'General Mills', 'CLX': 'Clorox',
    'CHD': 'Church & Dwight', 'SJM': 'J.M. Smucker', 'KMB': 'Kimberly-Clark',
    'HRL': 'Hormel Foods', 'CAG': 'Conagra', 'CPB': 'Campbell Soup',
    'MKC': 'McCormick', 'HSY': 'Hershey', 'KR': 'Kroger', 'SYY': 'Sysco',
    'ADM': 'Archer-Daniels-Midland', 'TSN': 'Tyson Foods', 'BG': 'Bunge',
    'KVUE': 'Kenvue', 'EL': 'Estee Lauder', 'AMCR': 'Amcor',
    'DPZ': "Domino's Pizza", 'DRI': 'Darden Restaurants', 'EBAY': 'eBay',
    'HAS': 'Hasbro', 'HLT': 'Hilton', 'LVS': 'Las Vegas Sands',
    'MAR': 'Marriott', 'MGM': 'MGM Resorts', 'NCLH': 'Norwegian Cruise Line',
    'RCL': 'Royal Caribbean', 'RL': 'Ralph Lauren', 'TPR': 'Tapestry',
    'WYNN': 'Wynn Resorts', 'CCL': 'Carnival', 'WSM': 'Williams-Sonoma',
    'POOL': 'Pool Corp.', 'LW': 'Lamb Weston', 'NWS': 'News Corp Class B',
    'NWSA': 'News Corp Class A', 'TKO': 'TKO Group', 'LYV': 'Live Nation',
    'BF.B': 'Brown-Forman',
    // Mid-cap Consumer additions
    'TXRH': 'Texas Roadhouse', 'WING': 'Wingstop', 'SHAK': 'Shake Shack',
    'SG': 'Sweetgreen', 'LOCO': 'El Pollo Loco', 'DNUT': 'Krispy Kreme',
    'EAT': 'Brinker International', 'CAKE': 'Cheesecake Factory',
    'BJRI': "BJ's Restaurants", 'PLAY': "Dave & Buster's", 'DIN': 'Dine Brands',
    'JACK': 'Jack in the Box', 'ARCO': 'Arcos Dorados',
    'FIVE': 'Five Below', 'OLLI': "Ollie's Bargain", 'BJ': "BJ's Wholesale",
    'COLM': 'Columbia Sportswear', 'VFC': 'VF Corp.',
    'GIII': 'G-III Apparel', 'OXM': 'Oxford Industries',
    'PVH': 'PVH Corp.', 'COTY': 'Coty', 'MNSO': 'Miniso',
    'AEO': 'American Eagle', 'ANF': 'Abercrombie & Fitch', 'GAP': 'Gap Inc.',
    'VSCO': "Victoria's Secret", 'BBWI': 'Bath & Body Works', 'RVLV': 'Revolve',
    'WRBY': 'Warby Parker', 'M': "Macy's", 'KSS': "Kohl's", 'BURL': 'Burlington',
    'PENN': 'Penn Entertainment', 'CZR': 'Caesars Entertainment',
    'BYD': 'Boyd Gaming', 'GDEN': 'Golden Entertainment',
    'VAC': 'Marriott Vacations', 'MTN': 'Vail Resorts', 'FUN': 'Six Flags',
    'PRKS': 'United Parks & Resorts',
    // Energy
    'XOM': 'ExxonMobil', 'CVX': 'Chevron', 'COP': 'ConocoPhillips', 'SLB': 'SLB',
    'NEE': 'NextEra Energy', 'ENPH': 'Enphase', 'FSLR': 'First Solar', 'PLUG': 'Plug Power',
    'EOG': 'EOG Resources', 'OXY': 'Occidental Petroleum', 'MPC': 'Marathon Petroleum', 'PSX': 'Phillips 66',
    'VLO': 'Valero Energy', 'TRGP': 'Targa Resources', 'DVN': 'Devon Energy', 'FANG': 'Diamondback Energy',
    'WMB': 'Williams Companies', 'APA': 'APA Corporation', 'HAL': 'Halliburton', 'BKR': 'Baker Hughes',
    'NOV': 'NOV Inc.', 'FTI': 'TechnipFMC', 'DUK': 'Duke Energy', 'SO': 'Southern Company',
    'D': 'Dominion Energy', 'AEP': 'American Electric Power', 'EXC': 'Exelon', 'OKE': 'ONEOK',
    'SEDG': 'SolarEdge', 'RUN': 'Sunrun', 'PBF': 'PBF Energy', 'DK': 'Delek US',
    'CTRA': 'Coterra Energy', 'OVV': 'Ovintiv', 'PR': 'Permian Resources', 'SM': 'SM Energy',
    'MGY': 'Magnolia Oil', 'MTDR': 'Matador Resources', 'CHRD': 'Chord Energy', 'VNOM': 'Viper Energy',
    'EQT': 'EQT Corporation', 'SMR': 'NuScale Power', 'VST': 'Vistra', 'CEG': 'Constellation Energy',
    'CCJ': 'Cameco', 'LNG': 'Cheniere Energy', 'AR': 'Antero Resources', 'GEV': 'GE Vernova',
    // S&P 500 Energy/Utilities additions
    'SRE': 'Sempra', 'AES': 'AES Corp.', 'PCG': 'PG&E',
    'EIX': 'Edison International', 'XEL': 'Xcel Energy', 'WEC': 'WEC Energy',
    'ES': 'Eversource Energy', 'ETR': 'Entergy', 'PEG': 'PSEG',
    'ED': 'Consolidated Edison', 'FE': 'FirstEnergy', 'CNP': 'CenterPoint',
    'PPL': 'PPL Corp.', 'AEE': 'Ameren', 'ATO': 'Atmos Energy',
    'DTE': 'DTE Energy', 'CMS': 'CMS Energy', 'EVRG': 'Evergy',
    'NI': 'NiSource', 'LNT': 'Alliant Energy', 'NRG': 'NRG Energy',
    'PNW': 'Pinnacle West', 'AWK': 'American Water Works',
    'KMI': 'Kinder Morgan', 'TPL': 'Texas Pacific Land', 'EXE': 'Expand Energy',
    // Mid-cap Energy/Clean Energy additions
    'ARRY': 'Array Technologies', 'MAXN': 'Maxeon Solar', 'BE': 'Bloom Energy',
    'STEM': 'Stem Inc.', 'SHLS': 'Shoals Technologies',
    'ORA': 'Ormat Technologies', 'CWEN': 'Clearway Energy', 'TAC': 'TransAlta',
    'CNX': 'CNX Resources', 'RRC': 'Range Resources', 'WFRD': 'Weatherford',
    'LBRT': 'Liberty Energy', 'PTEN': 'Patterson-UTI',
    'HP': 'Helmerich & Payne',
    'NFE': 'New Fortress Energy', 'AMPY': 'Amplify Energy', 'EE': 'Excelerate Energy',
    'LEU': 'Centrus Energy',
    // Industrials
    'BA': 'Boeing', 'CAT': 'Caterpillar', 'DE': 'Deere & Co.', 'GE': 'GE Aerospace',
    'HON': 'Honeywell', 'UPS': 'United Parcel Service', 'FDX': 'FedEx',
    'MMM': '3M', 'UNP': 'Union Pacific', 'NSC': 'Norfolk Southern', 'CSX': 'CSX Corporation',
    'CHRW': 'C.H. Robinson', 'CMI': 'Cummins', 'EMR': 'Emerson Electric', 'ETN': 'Eaton',
    'PH': 'Parker Hannifin', 'ROK': 'Rockwell Automation', 'AME': 'Ametek', 'DOV': 'Dover', 'ITW': 'Illinois Tool Works',
    'DHI': 'D.R. Horton', 'LEN': 'Lennar', 'NVR': 'NVR Inc.', 'PHM': 'PulteGroup',
    'TOL': 'Toll Brothers', 'BLD': 'TopBuild', 'BLDR': 'Builders FirstSource',
    'JBHT': 'J.B. Hunt', 'KNX': 'Knight-Swift', 'ODFL': 'Old Dominion Freight', 'XPO': 'XPO',
    'IR': 'Ingersoll Rand', 'WM': 'WM', 'RSG': 'Republic Services',
    'PCAR': 'Paccar', 'PWR': 'Quanta Services', 'JCI': 'Johnson Controls',
    'AOS': 'A.O. Smith', 'ROP': 'Roper Technologies', 'CARR': 'Carrier Global', 'VLTO': 'Veralto',
    'ROCK': 'Gibraltar Industries', 'MLI': 'Mueller Industries', 'RUSHA': 'Rush Enterprises',
    'MYRG': 'MYR Group', 'DY': 'Dycom Industries', 'APOG': 'Apogee Enterprises',
    'VRT': 'Vertiv Holdings', 'EME': 'EMCOR Group', 'APH': 'Amphenol',
    'HUBB': 'Hubbell', 'WCC': 'WESCO International', 'TT': 'Trane Technologies', 'GNRC': 'Generac Holdings',
    'GEO': 'GEO Group', 'CXW': 'CoreCivic',
    // S&P 500 Industrials additions
    'ADP': 'Automatic Data Processing', 'OTIS': 'Otis Worldwide', 'CTAS': 'Cintas',
    'WAB': 'Wabtec', 'FAST': 'Fastenal', 'URI': 'United Rentals',
    'CPRT': 'Copart', 'GWW': 'W.W. Grainger', 'FIX': 'Comfort Systems USA',
    'ROL': 'Rollins', 'ALLE': 'Allegion', 'SNA': 'Snap-on',
    'SWK': 'Stanley Black & Decker', 'PNR': 'Pentair', 'PAYX': 'Paychex',
    'DAL': 'Delta Air Lines', 'UAL': 'United Airlines', 'LUV': 'Southwest Airlines',
    'EXPD': 'Expeditors', 'LII': 'Lennox', 'PKG': 'Packaging Corp.',
    'AVY': 'Avery Dennison', 'MAS': 'Masco', 'IP': 'International Paper',
    'WY': 'Weyerhaeuser', 'BALL': 'Ball Corp.', 'FTV': 'Fortive',
    'IFF': 'IFF Inc.', 'BR': 'Broadridge Financial', 'J': 'Jacobs Solutions',
    'VMC': 'Vulcan Materials', 'MLM': 'Martin Marietta', 'CRH': 'CRH plc',
    'XYL': 'Xylem', 'SW': 'Smurfit Westrock',
    // Mid-cap Industrials additions
    'ACM': 'AECOM', 'MTZ': 'MasTec', 'STRL': 'Sterling Construction',
    'GVA': 'Granite Construction', 'ROAD': 'Construction Partners',
    'PRIM': 'Primoris', 'TPC': 'Tutor Perini', 'AGX': 'Argan Inc.',
    'UFPI': 'UFP Industries',
    'AWI': 'Armstrong World', 'TREX': 'Trex', 'SITE': 'SiteOne Landscape',
    'BFAM': 'Bright Horizons', 'HRI': 'Herc Holdings',
    'WSC': 'WillScot Mobile Mini', 'SKYW': 'SkyWest',
    'ALK': 'Alaska Air', 'JBLU': 'JetBlue', 'AAL': 'American Airlines',
    'SNDR': 'Schneider National', 'SAIA': 'Saia Inc.', 'ARCB': 'ArcBest',
    'WERN': 'Werner', 'HUBG': 'Hub Group', 'R': 'Ryder', 'GATX': 'GATX',
    'RXO': 'RXO Inc.', 'ATKR': 'Atkore', 'AIT': 'Applied Industrial',
    'REZI': 'Resideo', 'LECO': 'Lincoln Electric', 'MIDD': 'Middleby',
    'FELE': 'Franklin Electric', 'WTS': 'Watts Water', 'MWA': 'Mueller Water',
    'ESE': 'ESCO Technologies', 'IEX': 'IDEX Corp.',
    // Real Estate
    'AMT': 'American Tower', 'PLD': 'Prologis', 'EQIX': 'Equinix', 'O': 'Realty Income',
    'CCI': 'Crown Castle', 'PSA': 'Public Storage', 'DLR': 'Digital Realty', 'WELL': 'Welltower',
    'VICI': 'VICI Properties', 'SPG': 'Simon Property', 'AVB': 'AvalonBay', 'EQR': 'Equity Residential',
    'MAA': 'Mid-America Apartment', 'UDR': 'UDR Inc.', 'CPT': 'Camden Property', 'ESS': 'Essex Property',
    'ELS': 'Equity LifeStyle', 'SUI': 'Sun Communities', 'NXRT': 'NexPoint Residential',
    'VTR': 'Ventas', 'STWD': 'Starwood Property', 'DOC': 'Healthpeak', 'OHI': 'Omega Healthcare',
    'SBRA': 'Sabra Healthcare', 'LTC': 'LTC Properties', 'HR': 'Healthcare Realty', 'MPT': 'Medical Properties Trust',
    'NHI': 'National Health Investors', 'CTRE': 'CareTrust REIT', 'IRM': 'Iron Mountain', 'CUBE': 'CubeSmart',
    'NSA': 'National Storage', 'REXR': 'Rexford Industrial',
    'TRNO': 'Terreno Realty', 'SELF': 'Global Self Storage', 'SAFE': 'Safehold',
    // S&P 500 Real Estate additions
    'EXR': 'Extra Space Storage', 'ARE': 'Alexandria Real Estate',
    'KIM': 'Kimco Realty', 'REG': 'Regency Centers', 'INVH': 'Invitation Homes',
    'FRT': 'Federal Realty', 'HST': 'Host Hotels', 'BXP': 'BXP Inc.',
    'SBAC': 'SBA Communications',
    // Mid-cap Real Estate additions
    'GLPI': 'Gaming & Leisure Properties', 'SLG': 'SL Green', 'VNO': 'Vornado',
    'DEI': 'Douglas Emmett', 'CUZ': 'Cousins Properties', 'HIW': 'Highwoods',
    'CDP': 'COPT Defense Properties', 'NNN': 'NNN REIT', 'ADC': 'Agree Realty',
    'EPRT': 'Essential Properties', 'KRG': 'Kite Realty', 'AKR': 'Acadia Realty',
    'BNL': 'Broadstone Net Lease', 'GTY': 'Getty Realty',
    'IIPR': 'Innovative Industrial Properties', 'APLE': 'Apple Hospitality',
    'RLJ': 'RLJ Lodging', 'PEB': 'Pebblebrook Hotel', 'SHO': 'Sunstone Hotel',
    'DRH': 'DiamondRock', 'FR': 'First Industrial', 'STAG': 'STAG Industrial',
    'LXP': 'LXP Industrial', 'COLD': 'Americold', 'LAMR': 'Lamar Advertising',
    'OUT': 'Outfront Media',
    // Materials
    'NEM': 'Newmont', 'FCX': 'Freeport-McMoRan', 'NUE': 'Nucor', 'DOW': 'Dow Inc.',
    'USAR': 'USA Rare Earth', 'UUUU': 'Energy Fuels', 'NB': 'NioCorp Developments', 'MP': 'MP Materials',
    'GOLD': 'Barrick Gold', 'AU': 'AngloGold Ashanti', 'AEM': 'Agnico Eagle', 'WPM': 'Wheaton Precious Metals',
    'FNV': 'Franco-Nevada', 'RGLD': 'Royal Gold', 'KGC': 'Kinross Gold', 'HL': 'Hecla Mining',
    'STLD': 'Steel Dynamics', 'RS': 'Reliance Steel', 'CLF': 'Cleveland-Cliffs', 'MT': 'ArcelorMittal',
    'TX': 'Ternium', 'CMC': 'Commercial Metals', 'ATI': 'ATI Inc.', 'KALU': 'Kaiser Aluminum',
    'LYB': 'LyondellBasell', 'EMN': 'Eastman Chemical', 'CE': 'Celanese', 'DD': 'DuPont',
    'APD': 'Air Products', 'LIN': 'Linde', 'GTLS': 'Chart Industries', 'NUAI': 'New Era Helium', 'ASPI': 'ASP Isotopes', 'ECL': 'Ecolab',
    'SHW': 'Sherwin-Williams', 'PPG': 'PPG Industries', 'RPM': 'RPM International', 'AXTA': 'Axalta Coating',
    'ALB': 'Albemarle', 'SQM': 'SQM', 'LAC': 'Lithium Americas', 'AA': 'Alcoa',
    'FUL': 'H.B. Fuller', 'NEU': 'NewMarket', 'B': 'Barrick Mining',
    // S&P 500 Materials additions
    'CTVA': 'Corteva Agriscience', 'MOS': 'Mosaic', 'CF': 'CF Industries',
    // Mid-cap Materials additions
    'PAAS': 'Pan American Silver', 'AG': 'First Majestic', 'CDE': 'Coeur Mining',
    'EGO': 'Eldorado Gold', 'SSRM': 'SSR Mining', 'HBM': 'Hudbay Minerals',
    'TECK': 'Teck Resources', 'RIO': 'Rio Tinto', 'BHP': 'BHP Group',
    'VALE': 'Vale', 'SCCO': 'Southern Copper', 'GFI': 'Gold Fields',
    'BTG': 'B2Gold', 'IAUX': 'i-80 Gold', 'AMR': 'Alpha Metallurgical',
    'HCC': 'Warrior Met Coal', 'CNR': 'Core Natural Resources',
    'MEOH': 'Methanex', 'CC': 'Chemours', 'OLN': 'Olin', 'TROX': 'Tronox',
    'HUN': 'Huntsman', 'WLK': 'Westlake', 'CBT': 'Cabot', 'NGVT': 'Ingevity',
    'ASH': 'Ashland', 'SON': 'Sonoco', 'SEE': 'Sealed Air',
    'GPK': 'Graphic Packaging', 'SLVM': 'Sylvamo',
    // Defense
    'LMT': 'Lockheed Martin', 'RTX': 'RTX Corporation', 'NOC': 'Northrop Grumman', 'GD': 'General Dynamics',
    'LHX': 'L3Harris', 'HII': 'Huntington Ingalls', 'TXT': 'Textron', 'HWM': 'Howmet Aerospace',
    'AXON': 'Axon Enterprise', 'KTOS': 'Kratos Defense', 'AVAV': 'AeroVironment', 'AIR': 'AAR Corp',
    'SAIC': 'SAIC', 'LDOS': 'Leidos', 'CACI': 'CACI International', 'BAH': 'Booz Allen Hamilton',
    'BWXT': 'BWX Technologies', 'WWD': 'Woodward', 'TDG': 'TransDigm', 'HEI': 'HEICO',
    'CW': 'Curtiss-Wright', 'MOG.A': 'Moog', 'AIN': 'Albany International',
    'PSN': 'Parsons Corporation', 'MRCY': 'Mercury Systems', 'DRS': 'Leonardo DRS',
    'RCAT': 'Red Cat Holdings', 'JOBY': 'Joby Aviation', 'ACHR': 'Archer Aviation',
    // Mid-cap Defense additions
    'OSIS': 'OSI Systems', 'VSEC': 'VSE Corp.', 'BDC': 'Belden',
    // Space
    'RKLB': 'Rocket Lab', 'ASTS': 'AST SpaceMobile', 'LUNR': 'Intuitive Machines',
    'RDW': 'Redwire', 'BKSY': 'BlackSky Technology', 'SPIR': 'Spire Global',
    'IRDM': 'Iridium Communications', 'GSAT': 'Globalstar',
    // Crypto
    'COIN': 'Coinbase', 'MSTR': 'Strategy', 'MARA': 'MARA Holdings',
    'RIOT': 'Riot Platforms', 'CLSK': 'CleanSpark', 'HUT': 'Hut 8',
    'BTDR': 'Bitdeer Technologies', 'BITF': 'Bitfarms',
    // Crypto additions
    'CORZ': 'Core Scientific', 'WULF': 'TeraWulf', 'IREN': 'Iris Energy',
    'CIFR': 'Cipher Mining',
    // Chemicals
    'LXU': 'LSB Industries',

    // Index Funds
    'SPY': 'S&P 500 ETF', 'QQQ': 'Nasdaq 100 ETF', 'IWM': 'Russell 2000 ETF', 'VOO': 'Vanguard S&P 500',
    'VONG': 'Vanguard Russell 1000 Growth ETF', 'XMMO': 'Invesco S&P MidCap Momentum ETF',
    'SCHF': 'Schwab International Equity ETF', 'VSS': 'Vanguard FTSE All-World ex-US Small-Cap ETF',
    'SPEM': 'SPDR Portfolio Emerging Markets ETF', 'VOOG': 'Vanguard S&P 500 Growth ETF'
};

const stockSectors = {
    // Tech - AI/Software
    'NVDA': 'Technology', 'AMD': 'Technology', 'GOOGL': 'Technology', 'GOOG': 'Technology',
    'META': 'Technology', 'PLTR': 'Technology', 'SNOW': 'Technology', 'MSFT': 'Technology',
    'ORCL': 'Technology', 'CRM': 'Technology', 'ADBE': 'Technology', 'NOW': 'Technology',
    'AI': 'Technology', 'BBAI': 'Technology', 'SOUN': 'Technology', 'PATH': 'Technology',
    'S': 'Technology', 'HUBS': 'Technology', 'ZM': 'Technology', 'DOCU': 'Technology',
    'TEAM': 'Technology', 'WDAY': 'Technology', 'VEEV': 'Technology', 'ESTC': 'Technology',
    'DDOG': 'Technology', 'NET': 'Technology', 'MDB': 'Technology', 'CRWD': 'Technology',
    'PANW': 'Technology', 'ZS': 'Technology', 'OKTA': 'Technology', 'CFLT': 'Technology',
    'GTLB': 'Technology', 'FROG': 'Technology', 'BILL': 'Technology', 'DOCN': 'Technology',
    'MNDY': 'Technology', 'PCOR': 'Technology', 'APP': 'Technology', 'INTU': 'Technology',
    'FTNT': 'Technology', 'TENB': 'Technology', 'QLYS': 'Technology', 'RPD': 'Technology', 'VRNS': 'Technology',
    // S&P 500 Technology additions
    'ACN': 'Technology', 'ADSK': 'Technology', 'ANET': 'Technology', 'CSCO': 'Technology',
    'CTSH': 'Technology', 'EPAM': 'Technology', 'FFIV': 'Technology', 'FICO': 'Technology',
    'GDDY': 'Technology', 'GEN': 'Technology', 'GLW': 'Technology', 'HPE': 'Technology',
    'JBL': 'Technology', 'KEYS': 'Technology', 'MSI': 'Technology',
    'PAYC': 'Technology', 'PTC': 'Technology', 'TEL': 'Technology', 'TER': 'Technology',
    'TRMB': 'Technology', 'TTD': 'Technology', 'TYL': 'Technology',
    'VRSN': 'Technology', 'ZBRA': 'Technology', 'CDW': 'Technology',
    'AKAM': 'Technology', 'CIEN': 'Technology', 'CSGP': 'Technology', 'NDSN': 'Technology',
    'TDY': 'Technology',
    'GRMN': 'Technology', 'IT': 'Technology', 'CHTR': 'Technology',
    // Technology - Gaming/Media
    'EA': 'Technology', 'TTWO': 'Technology', 'FOX': 'Consumer', 'MTCH': 'Technology',
    // Mid-cap Technology additions
    'CRDO': 'Technology', 'RMBS': 'Technology', 'LSCC': 'Technology',
    'MTSI': 'Technology', 'DIOD': 'Technology', 'NTNX': 'Technology',
    'ASAN': 'Technology', 'FIVN': 'Technology', 'RBRK': 'Technology',
    'GTM': 'Technology', 'DT': 'Technology',
    'TWLO': 'Technology', 'DBX': 'Technology', 'BOX': 'Technology',
    'YOU': 'Technology', 'SMTC': 'Technology', 'CALX': 'Technology', 'PI': 'Technology',
    'MANH': 'Technology', 'GWRE': 'Technology', 'WK': 'Technology',
    'BSY': 'Technology', 'APPF': 'Technology', 'PCTY': 'Technology',
    // Tech - Hardware/Semiconductors
    'AAPL': 'Technology', 'QCOM': 'Technology', 'INTC': 'Technology', 'MU': 'Technology',
    'ARM': 'Technology', 'AVGO': 'Technology', 'TXN': 'Technology', 'ADI': 'Technology',
    'NXPI': 'Technology', 'KLAC': 'Technology', 'ASML': 'Technology', 'TSM': 'Technology',
    'SNPS': 'Technology', 'CDNS': 'Technology', 'ON': 'Technology', 'MPWR': 'Technology',
    'SWKS': 'Technology', 'QRVO': 'Technology', 'DELL': 'Technology', 'HPQ': 'Technology',
    'AMAT': 'Technology', 'LRCX': 'Technology', 'MRVL': 'Technology', 'ENTG': 'Technology',
    'FORM': 'Technology', 'MKSI': 'Technology', 'COHR': 'Technology', 'IPGP': 'Technology',
    'LITE': 'Technology', 'AMBA': 'Technology', 'SLAB': 'Technology', 'CRUS': 'Technology',
    'SYNA': 'Technology', 'MCHP': 'Technology', 'SMCI': 'Technology', 'WDC': 'Technology',
    'STX': 'Technology', 'PSTG': 'Technology', 'NTAP': 'Technology', 'CHKP': 'Technology',
    'IONQ': 'Technology', 'RGTI': 'Technology', 'QBTS': 'Technology', 'QUBT': 'Technology',
    'ARQQ': 'Technology', 'IBM': 'Technology', 'WOLF': 'Technology', 'OUST': 'Technology',
    'IMOS': 'Technology', 'VECO': 'Technology', 'POWI': 'Technology', 'PLXS': 'Technology', 'VICR': 'Technology',
    // EV/Automotive
    'TSLA': 'Automotive', 'RIVN': 'Automotive', 'LCID': 'Automotive', 'NIO': 'Automotive',
    'XPEV': 'Automotive', 'LI': 'Automotive', 'F': 'Automotive', 'GM': 'Automotive',
    'STLA': 'Automotive', 'TM': 'Automotive', 'HMC': 'Automotive', 'RACE': 'Automotive',
    'BLNK': 'Automotive', 'CHPT': 'Automotive', 'EVGO': 'Automotive', 'PAG': 'Automotive',
    'QS': 'Automotive', 'ALV': 'Automotive', 'CVNA': 'Automotive', 'KMX': 'Automotive',
    'APTV': 'Automotive', 'AN': 'Automotive', 'LAD': 'Automotive',
    // Finance
    'JPM': 'Financial', 'BAC': 'Financial', 'V': 'Financial', 'MA': 'Financial',
    'SOFI': 'Financial', 'PYPL': 'Financial', 'XYZ': 'Financial', 'GPN': 'Financial',
    'WFC': 'Financial', 'GS': 'Financial', 'MS': 'Financial', 'C': 'Financial',
    'BLK': 'Financial', 'SCHW': 'Financial', 'AFRM': 'Financial', 'UPST': 'Financial',
    'LC': 'Financial', 'NU': 'Financial', 'MELI': 'Financial', 'HOOD': 'Financial',
    'AXP': 'Financial', 'FIS': 'Financial', 'COF': 'Financial', 'ALLY': 'Financial',
    'USB': 'Financial', 'PNC': 'Financial', 'TFC': 'Financial', 'RF': 'Financial',
    'KEY': 'Financial', 'FITB': 'Financial', 'CFG': 'Financial', 'HBAN': 'Financial',
    'MTB': 'Financial', 'STT': 'Financial', 'BK': 'Financial', 'NTRS': 'Financial',
    'ZION': 'Financial', 'FHN': 'Financial',
    'WRB': 'Financial', 'CB': 'Financial', 'TRV': 'Financial', 'ALL': 'Financial',
    'PGR': 'Financial', 'AIG': 'Financial', 'MET': 'Financial', 'PRU': 'Financial',
    'RKT': 'Financial', 'FOUR': 'Financial', 'PAYO': 'Financial', 'DLO': 'Financial',
    'RELY': 'Financial', 'FLYW': 'Financial',
    // S&P 500 Financial additions
    'SPGI': 'Financial', 'ICE': 'Financial', 'CME': 'Financial',
    'MCO': 'Financial', 'MSCI': 'Financial', 'NDAQ': 'Financial',
    'AON': 'Financial', 'AJG': 'Financial', 'ACGL': 'Financial',
    'AFL': 'Financial', 'CINF': 'Financial', 'BRO': 'Financial',
    'GL': 'Financial', 'ERIE': 'Financial', 'EG': 'Financial',
    'BRK.B': 'Financial', 'BX': 'Financial', 'KKR': 'Financial',
    'APO': 'Financial', 'ARES': 'Financial', 'IBKR': 'Financial',
    'PFG': 'Financial', 'L': 'Financial', 'BEN': 'Financial',
    'IVZ': 'Financial', 'SYF': 'Financial', 'CBOE': 'Financial',
    'RJF': 'Financial', 'AMP': 'Financial', 'TROW': 'Financial',
    'FISV': 'Financial', 'HIG': 'Financial', 'CPAY': 'Financial', 'AIZ': 'Financial', 'JKHY': 'Financial',
    'CBRE': 'Financial', 'FDS': 'Financial', 'VRSK': 'Financial',
    'WTW': 'Financial', 'EFX': 'Financial',
    // Mid-cap Financial additions
    'WAL': 'Financial', 'EWBC': 'Financial',
    'FNB': 'Financial', 'WTFC': 'Financial', 'PNFP': 'Financial',
    'SSB': 'Financial', 'BOKF': 'Financial', 'GBCI': 'Financial',
    'FLG': 'Financial', 'OZK': 'Financial',
    'SBCF': 'Financial', 'UMBF': 'Financial',
    'FCNCA': 'Financial', 'FNF': 'Financial',
    'FAF': 'Financial', 'ESNT': 'Financial',
    'RDN': 'Financial', 'KNSL': 'Financial', 'RLI': 'Financial',
    'ORI': 'Financial', 'THG': 'Financial',
    'AFG': 'Financial', 'RYAN': 'Financial',
    'JEF': 'Financial', 'EVR': 'Financial', 'PJT': 'Financial',
    'HLI': 'Financial', 'LPLA': 'Financial', 'PIPR': 'Financial',
    'SF': 'Financial', 'MKTX': 'Financial', 'VIRT': 'Financial', 'TW': 'Financial',
    // Growth Tech/Consumer (mixed sector assignments)
    'DKNG': 'Technology', 'RBLX': 'Technology', 'U': 'Technology', 'PINS': 'Technology',
    'SNAP': 'Technology', 'SPOT': 'Technology', 'ABNB': 'Consumer',
    'LYFT': 'Technology', 'DASH': 'Consumer', 'UBER': 'Technology', 'CPNG': 'Consumer',
    'SHOP': 'Technology', 'SE': 'Consumer', 'BABA': 'Consumer', 'JD': 'Consumer',
    'PDD': 'Consumer', 'BKNG': 'Consumer', 'EXPE': 'Consumer', 'TCOM': 'Consumer', 'TRIP': 'Consumer',
    'PTON': 'Consumer', 'OPEN': 'Technology', 'COMP': 'Technology',
    'CWAN': 'Technology', 'DUOL': 'Technology', 'BROS': 'Consumer', 'CAVA': 'Consumer',
    'TOST': 'Technology', 'GLBE': 'Technology', 'CART': 'Technology',
    'GRAB': 'Technology', 'IOT': 'Technology', 'BRZE': 'Technology',
    'ONON': 'Consumer', 'BIRK': 'Consumer',
    // Healthcare
    'JNJ': 'Healthcare', 'UNH': 'Healthcare', 'LLY': 'Healthcare', 'PFE': 'Healthcare',
    'MRNA': 'Healthcare', 'ABBV': 'Healthcare', 'VRTX': 'Healthcare', 'REGN': 'Healthcare',
    'BMY': 'Healthcare', 'GILD': 'Healthcare', 'AMGN': 'Healthcare', 'CVS': 'Healthcare',
    'CI': 'Healthcare', 'HUM': 'Healthcare', 'ISRG': 'Healthcare', 'TMO': 'Healthcare',
    'DHR': 'Healthcare', 'ABT': 'Healthcare', 'SYK': 'Healthcare', 'BSX': 'Healthcare',
    'MDT': 'Healthcare', 'BDX': 'Healthcare', 'BAX': 'Healthcare', 'ZBH': 'Healthcare',
    'HCA': 'Healthcare', 'DVA': 'Healthcare',
    'EXAS': 'Healthcare', 'ILMN': 'Healthcare', 'BIIB': 'Healthcare', 'ALNY': 'Healthcare',
    'INCY': 'Healthcare', 'NBIX': 'Healthcare', 'UTHR': 'Healthcare', 'JAZZ': 'Healthcare',
    'SRPT': 'Healthcare', 'BMRN': 'Healthcare', 'IONS': 'Healthcare', 'RGEN': 'Healthcare',
    'CRSP': 'Healthcare', 'NTLA': 'Healthcare', 'BEAM': 'Healthcare',
    'RXRX': 'Healthcare', 'TWST': 'Healthcare', 'PACB': 'Healthcare',
    'EDIT': 'Healthcare', 'IOVA': 'Healthcare', 'PCVX': 'Healthcare',
    'MDGL': 'Healthcare', 'TGTX': 'Healthcare', 'LEGN': 'Healthcare',
    'DNA': 'Healthcare', 'FATE': 'Healthcare',
    'HIMS': 'Healthcare', 'DOCS': 'Healthcare', 'OSCR': 'Healthcare',
    'ZTS': 'Healthcare', 'WAT': 'Healthcare',
    // S&P 500 Healthcare additions
    'MRK': 'Healthcare', 'A': 'Healthcare', 'IQV': 'Healthcare',
    'GEHC': 'Healthcare', 'HOLX': 'Healthcare', 'DXCM': 'Healthcare',
    'IDXX': 'Healthcare', 'PODD': 'Healthcare', 'ALGN': 'Healthcare',
    'EW': 'Healthcare', 'COO': 'Healthcare',
    'MTD': 'Healthcare', 'WST': 'Healthcare', 'TECH': 'Healthcare',
    'CNC': 'Healthcare', 'MOH': 'Healthcare', 'COR': 'Healthcare',
    'CAH': 'Healthcare', 'MCK': 'Healthcare', 'VTRS': 'Healthcare',
    'LH': 'Healthcare', 'DGX': 'Healthcare', 'RMD': 'Healthcare',
    'ELV': 'Healthcare', 'STE': 'Healthcare', 'HSIC': 'Healthcare',
    'UHS': 'Healthcare', 'CRL': 'Healthcare', 'RVTY': 'Healthcare', 'SOLV': 'Healthcare',
    // Mid-cap Healthcare additions
    'NVCR': 'Healthcare', 'GKOS': 'Healthcare', 'NVST': 'Healthcare',
    'XRAY': 'Healthcare', 'TFX': 'Healthcare', 'MMSI': 'Healthcare',
    'PEN': 'Healthcare', 'LNTH': 'Healthcare', 'AZTA': 'Healthcare',
    'NEOG': 'Healthcare', 'PRCT': 'Healthcare', 'IRTC': 'Healthcare',
    'HALO': 'Healthcare', 'INSM': 'Healthcare', 'RARE': 'Healthcare',
    'PTCT': 'Healthcare', 'ARWR': 'Healthcare',
    'FOLD': 'Healthcare', 'MYGN': 'Healthcare',
    'GH': 'Healthcare', 'NTRA': 'Healthcare', 'SDGR': 'Healthcare', 'VERA': 'Healthcare',
    // Consumer
    'AMZN': 'Consumer', 'WMT': 'Consumer', 'COST': 'Consumer', 'TGT': 'Consumer',
    'HD': 'Consumer', 'LOW': 'Consumer', 'SBUX': 'Consumer', 'MCD': 'Consumer',
    'CMG': 'Consumer', 'YUM': 'Consumer', 'NKE': 'Consumer', 'LULU': 'Consumer',
    'ETSY': 'Consumer', 'W': 'Consumer', 'CHWY': 'Consumer',
    'DIS': 'Consumer', 'NFLX': 'Consumer', 'ROKU': 'Consumer', 'CARR': 'Industrials', 'WBD': 'Consumer',
    'FOXA': 'Consumer', 'CMCSA': 'Consumer', 'OMC': 'Consumer',
    'T': 'Consumer', 'VZ': 'Consumer', 'TMUS': 'Consumer',
    'KO': 'Consumer', 'PEP': 'Consumer', 'PM': 'Consumer', 'MO': 'Consumer',
    'BUD': 'Consumer', 'TAP': 'Consumer', 'STZ': 'Consumer', 'MNST': 'Consumer',
    'CELH': 'Consumer', 'KDP': 'Consumer', 'ULTA': 'Consumer', 'ELF': 'Consumer',
    'RH': 'Consumer', 'DECK': 'Consumer', 'CROX': 'Consumer', 'LEVI': 'Consumer',
    'UAA': 'Consumer', 'ORLY': 'Consumer', 'AZO': 'Consumer', 'AAP': 'Consumer',
    'GPC': 'Consumer', 'TSCO': 'Consumer', 'DG': 'Consumer', 'DLTR': 'Consumer',
    'ROST': 'Consumer', 'TJX': 'Consumer', 'BBY': 'Consumer',
    // S&P 500 Consumer additions
    'PG': 'Consumer', 'CL': 'Consumer', 'KHC': 'Consumer',
    'MDLZ': 'Consumer', 'GIS': 'Consumer', 'CLX': 'Consumer',
    'CHD': 'Consumer', 'SJM': 'Consumer', 'KMB': 'Consumer',
    'HRL': 'Consumer', 'CAG': 'Consumer', 'CPB': 'Consumer',
    'MKC': 'Consumer', 'HSY': 'Consumer', 'KR': 'Consumer', 'SYY': 'Consumer',
    'ADM': 'Consumer', 'TSN': 'Consumer', 'BG': 'Consumer',
    'KVUE': 'Consumer', 'EL': 'Consumer', 'AMCR': 'Consumer',
    'DPZ': 'Consumer', 'DRI': 'Consumer', 'EBAY': 'Consumer',
    'HAS': 'Consumer', 'HLT': 'Consumer', 'LVS': 'Consumer',
    'MAR': 'Consumer', 'MGM': 'Consumer', 'NCLH': 'Consumer',
    'RCL': 'Consumer', 'RL': 'Consumer', 'TPR': 'Consumer',
    'WYNN': 'Consumer', 'CCL': 'Consumer', 'WSM': 'Consumer',
    'POOL': 'Consumer', 'LW': 'Consumer', 'NWS': 'Consumer',
    'NWSA': 'Consumer', 'TKO': 'Consumer', 'LYV': 'Consumer', 'BF.B': 'Consumer',
    // Mid-cap Consumer additions
    'TXRH': 'Consumer', 'WING': 'Consumer', 'SHAK': 'Consumer',
    'SG': 'Consumer', 'LOCO': 'Consumer', 'DNUT': 'Consumer',
    'EAT': 'Consumer', 'CAKE': 'Consumer',
    'BJRI': 'Consumer', 'PLAY': 'Consumer', 'DIN': 'Consumer',
    'JACK': 'Consumer', 'ARCO': 'Consumer',
    'FIVE': 'Consumer', 'OLLI': 'Consumer', 'BJ': 'Consumer',
    'COLM': 'Consumer', 'VFC': 'Consumer',
    'GIII': 'Consumer', 'OXM': 'Consumer',
    'PVH': 'Consumer', 'COTY': 'Consumer', 'MNSO': 'Consumer',
    'AEO': 'Consumer', 'ANF': 'Consumer', 'GAP': 'Consumer',
    'VSCO': 'Consumer', 'BBWI': 'Consumer', 'RVLV': 'Consumer',
    'WRBY': 'Consumer', 'M': 'Consumer', 'KSS': 'Consumer', 'BURL': 'Consumer',
    'PENN': 'Consumer', 'CZR': 'Consumer',
    'BYD': 'Consumer', 'GDEN': 'Consumer',
    'VAC': 'Consumer', 'MTN': 'Consumer', 'FUN': 'Consumer', 'PRKS': 'Consumer',
    // Energy
    'XOM': 'Energy', 'CVX': 'Energy', 'COP': 'Energy', 'SLB': 'Energy',
    'EOG': 'Energy', 'OXY': 'Energy', 'MPC': 'Energy', 'PSX': 'Energy',
    'VLO': 'Energy', 'TRGP': 'Energy', 'DVN': 'Energy', 'FANG': 'Energy',
    'WMB': 'Energy', 'APA': 'Energy', 'HAL': 'Energy', 'BKR': 'Energy',
    'NOV': 'Energy', 'FTI': 'Energy', 'NEE': 'Energy', 'DUK': 'Energy',
    'SO': 'Energy', 'D': 'Energy', 'AEP': 'Energy', 'EXC': 'Energy', 'OKE': 'Energy',
    'ENPH': 'Energy', 'SEDG': 'Energy', 'RUN': 'Energy',
    'FSLR': 'Energy', 'PLUG': 'Energy', 'PBF': 'Energy', 'DK': 'Energy',
    'CTRA': 'Energy', 'OVV': 'Energy', 'PR': 'Energy', 'SM': 'Energy',
    'MGY': 'Energy', 'MTDR': 'Energy', 'CHRD': 'Energy', 'VNOM': 'Energy',
    'SMR': 'Energy', 'VST': 'Energy', 'CEG': 'Energy', 'CCJ': 'Energy',
    'LNG': 'Energy', 'AR': 'Energy', 'GEV': 'Energy', 'EQT': 'Energy',
    // S&P 500 Energy/Utilities additions
    'SRE': 'Energy', 'AES': 'Energy', 'PCG': 'Energy',
    'EIX': 'Energy', 'XEL': 'Energy', 'WEC': 'Energy',
    'ES': 'Energy', 'ETR': 'Energy', 'PEG': 'Energy',
    'ED': 'Energy', 'FE': 'Energy', 'CNP': 'Energy',
    'PPL': 'Energy', 'AEE': 'Energy', 'ATO': 'Energy',
    'DTE': 'Energy', 'CMS': 'Energy', 'EVRG': 'Energy',
    'NI': 'Energy', 'LNT': 'Energy', 'NRG': 'Energy',
    'PNW': 'Energy', 'AWK': 'Energy',
    'KMI': 'Energy', 'TPL': 'Energy', 'EXE': 'Energy',
    // Mid-cap Energy/Clean Energy additions
    'ARRY': 'Energy', 'MAXN': 'Energy', 'BE': 'Energy',
    'STEM': 'Energy', 'SHLS': 'Energy',
    'ORA': 'Energy', 'CWEN': 'Energy', 'TAC': 'Energy',
    'CNX': 'Energy', 'RRC': 'Energy', 'WFRD': 'Energy',
    'LBRT': 'Energy', 'PTEN': 'Energy', 'HP': 'Energy',
    // Industrials
    'BA': 'Industrials', 'CAT': 'Industrials', 'DE': 'Industrials', 'GE': 'Industrials',
    'HON': 'Industrials', 'MMM': 'Industrials', 'UNP': 'Industrials', 'NSC': 'Industrials',
    'CSX': 'Industrials', 'UPS': 'Industrials', 'FDX': 'Industrials', 'CHRW': 'Industrials',
    'CMI': 'Industrials', 'EMR': 'Industrials', 'ETN': 'Industrials', 'PH': 'Industrials',
    'ROK': 'Industrials', 'AME': 'Industrials', 'DOV': 'Industrials', 'ITW': 'Industrials',
    'DHI': 'Industrials', 'LEN': 'Industrials', 'NVR': 'Industrials', 'PHM': 'Industrials',
    'TOL': 'Industrials', 'BLD': 'Industrials', 'BLDR': 'Industrials', 'JBHT': 'Industrials',
    'KNX': 'Industrials', 'ODFL': 'Industrials', 'XPO': 'Industrials',
    'IR': 'Industrials', 'WM': 'Industrials', 'RSG': 'Industrials',
    'PCAR': 'Industrials', 'PWR': 'Industrials', 'JCI': 'Industrials',
    'AOS': 'Industrials', 'ROP': 'Industrials', 'VLTO': 'Industrials',
    'VRT': 'Industrials', 'EME': 'Industrials', 'APH': 'Industrials',
    'HUBB': 'Industrials', 'WCC': 'Industrials', 'TT': 'Industrials', 'GNRC': 'Industrials',
    'GEO': 'Industrials', 'CXW': 'Industrials',
    'ROCK': 'Industrials', 'MLI': 'Industrials', 'RUSHA': 'Industrials',
    'MYRG': 'Industrials', 'DY': 'Industrials', 'APOG': 'Industrials',
    // S&P 500 Industrials additions
    'ADP': 'Industrials', 'OTIS': 'Industrials', 'CTAS': 'Industrials',
    'WAB': 'Industrials', 'FAST': 'Industrials', 'URI': 'Industrials',
    'CPRT': 'Industrials', 'GWW': 'Industrials', 'FIX': 'Industrials',
    'ROL': 'Industrials', 'ALLE': 'Industrials', 'SNA': 'Industrials',
    'SWK': 'Industrials', 'PNR': 'Industrials', 'PAYX': 'Industrials',
    'DAL': 'Industrials', 'UAL': 'Industrials', 'LUV': 'Industrials',
    'EXPD': 'Industrials', 'LII': 'Industrials', 'PKG': 'Industrials',
    'AVY': 'Industrials', 'MAS': 'Industrials', 'IP': 'Industrials',
    'WY': 'Industrials', 'BALL': 'Industrials', 'FTV': 'Industrials',
    'IFF': 'Industrials', 'BR': 'Industrials', 'J': 'Industrials',
    'VMC': 'Industrials', 'MLM': 'Industrials', 'CRH': 'Industrials',
    'XYL': 'Industrials', 'SW': 'Industrials',
    // Mid-cap Industrials additions
    'ACM': 'Industrials', 'MTZ': 'Industrials', 'STRL': 'Industrials',
    'GVA': 'Industrials', 'ROAD': 'Industrials',
    'PRIM': 'Industrials', 'TPC': 'Industrials', 'AGX': 'Industrials',
    'UFPI': 'Industrials',
    'AWI': 'Industrials', 'TREX': 'Industrials', 'SITE': 'Industrials',
    'BFAM': 'Industrials', 'HRI': 'Industrials',
    'WSC': 'Industrials', 'SKYW': 'Industrials',
    'ALK': 'Industrials', 'JBLU': 'Industrials', 'AAL': 'Industrials',
    'SNDR': 'Industrials', 'SAIA': 'Industrials', 'ARCB': 'Industrials',
    'WERN': 'Industrials', 'HUBG': 'Industrials', 'R': 'Industrials', 'GATX': 'Industrials',
    'RXO': 'Industrials', 'ATKR': 'Industrials', 'AIT': 'Industrials',
    'REZI': 'Industrials', 'LECO': 'Industrials', 'MIDD': 'Industrials',
    'FELE': 'Industrials', 'WTS': 'Industrials', 'MWA': 'Industrials', 'ESE': 'Industrials',
    'IEX': 'Industrials',
    // Real Estate
    'AMT': 'Real Estate', 'PLD': 'Real Estate', 'CCI': 'Real Estate', 'EQIX': 'Real Estate',
    'PSA': 'Real Estate', 'DLR': 'Real Estate', 'WELL': 'Real Estate', 'O': 'Real Estate',
    'VICI': 'Real Estate', 'SPG': 'Real Estate', 'AVB': 'Real Estate', 'EQR': 'Real Estate',
    'MAA': 'Real Estate', 'UDR': 'Real Estate', 'CPT': 'Real Estate', 'ESS': 'Real Estate',
    'ELS': 'Real Estate', 'SUI': 'Real Estate', 'NXRT': 'Real Estate',
    'VTR': 'Real Estate', 'STWD': 'Real Estate', 'DOC': 'Real Estate', 'OHI': 'Real Estate',
    'SBRA': 'Real Estate', 'LTC': 'Real Estate', 'HR': 'Real Estate', 'MPT': 'Real Estate',
    'NHI': 'Real Estate', 'CTRE': 'Real Estate', 'IRM': 'Real Estate', 'CUBE': 'Real Estate',
    'NSA': 'Real Estate', 'REXR': 'Real Estate',
    'TRNO': 'Real Estate', 'SELF': 'Real Estate', 'SAFE': 'Real Estate',
    // S&P 500 Real Estate additions
    'EXR': 'Real Estate', 'ARE': 'Real Estate',
    'KIM': 'Real Estate', 'REG': 'Real Estate', 'INVH': 'Real Estate',
    'FRT': 'Real Estate', 'HST': 'Real Estate', 'BXP': 'Real Estate', 'SBAC': 'Real Estate',
    // Mid-cap Real Estate additions
    'GLPI': 'Real Estate', 'SLG': 'Real Estate', 'VNO': 'Real Estate',
    'DEI': 'Real Estate', 'CUZ': 'Real Estate', 'HIW': 'Real Estate',
    'CDP': 'Real Estate', 'NNN': 'Real Estate', 'ADC': 'Real Estate',
    'EPRT': 'Real Estate', 'KRG': 'Real Estate', 'AKR': 'Real Estate',
    'BNL': 'Real Estate', 'GTY': 'Real Estate',
    'IIPR': 'Real Estate', 'APLE': 'Real Estate',
    'RLJ': 'Real Estate', 'PEB': 'Real Estate', 'SHO': 'Real Estate',
    'DRH': 'Real Estate', 'FR': 'Real Estate', 'STAG': 'Real Estate',
    'LXP': 'Real Estate', 'COLD': 'Real Estate', 'LAMR': 'Real Estate', 'OUT': 'Real Estate',
    // Materials
    'NEM': 'Materials', 'FCX': 'Materials', 'GOLD': 'Materials', 'AU': 'Materials',
    'AEM': 'Materials', 'WPM': 'Materials', 'FNV': 'Materials', 'RGLD': 'Materials',
    'KGC': 'Materials', 'HL': 'Materials', 'NUE': 'Materials', 'STLD': 'Materials',
    'RS': 'Materials', 'CLF': 'Materials', 'MT': 'Materials',
    'TX': 'Materials', 'CMC': 'Materials', 'NB': 'Materials', 'ATI': 'Materials',
    'DOW': 'Materials', 'LYB': 'Materials', 'EMN': 'Materials', 'CE': 'Materials',
    'APD': 'Materials', 'LIN': 'Materials', 'GTLS': 'Materials', 'NUAI': 'Materials', 'ASPI': 'Materials', 'ECL': 'Materials',
    'SHW': 'Materials', 'PPG': 'Materials', 'RPM': 'Materials', 'AXTA': 'Materials',
    'ALB': 'Materials', 'SQM': 'Materials', 'LAC': 'Materials', 'AA': 'Materials',
    'MP': 'Materials', 'DD': 'Materials', 'USAR': 'Materials',
    'FUL': 'Materials', 'NEU': 'Materials', 'UUUU': 'Materials', 'B': 'Materials',
    // S&P 500 Materials additions
    'CTVA': 'Materials', 'MOS': 'Materials', 'CF': 'Materials',
    // Mid-cap Materials additions
    'PAAS': 'Materials', 'AG': 'Materials', 'CDE': 'Materials',
    'EGO': 'Materials', 'SSRM': 'Materials', 'HBM': 'Materials',
    'TECK': 'Materials', 'RIO': 'Materials', 'BHP': 'Materials',
    'VALE': 'Materials', 'SCCO': 'Materials', 'GFI': 'Materials',
    'BTG': 'Materials', 'IAUX': 'Materials', 'AMR': 'Materials',
    'HCC': 'Materials', 'CNR': 'Materials',
    'MEOH': 'Materials', 'CC': 'Materials', 'OLN': 'Materials', 'TROX': 'Materials',
    'HUN': 'Materials', 'WLK': 'Materials', 'CBT': 'Materials', 'NGVT': 'Materials',
    'ASH': 'Materials', 'SON': 'Materials', 'SEE': 'Materials',
    'GPK': 'Materials', 'SLVM': 'Materials',
    // Defense
    'LMT': 'Defense', 'RTX': 'Defense', 'NOC': 'Defense', 'GD': 'Defense',
    'LHX': 'Defense', 'HII': 'Defense', 'TXT': 'Defense', 'HWM': 'Defense',
    'AXON': 'Defense', 'KTOS': 'Defense', 'AVAV': 'Defense', 'AIR': 'Defense',
    'SAIC': 'Defense', 'LDOS': 'Defense', 'CACI': 'Defense', 'BAH': 'Defense',
    'BWXT': 'Defense', 'WWD': 'Defense', 'MOG.A': 'Defense', 'TDG': 'Defense',
    'HEI': 'Defense', 'CW': 'Defense', 'AIN': 'Defense',
    'PSN': 'Defense', 'MRCY': 'Defense', 'DRS': 'Defense',
    'RCAT': 'Defense', 'JOBY': 'Defense', 'ACHR': 'Defense',
    // Mid-cap Defense additions
    'OSIS': 'Defense', 'VSEC': 'Defense', 'BDC': 'Defense',
    // Space
    'RKLB': 'Space', 'ASTS': 'Space', 'LUNR': 'Space', 'RDW': 'Space',
    'BKSY': 'Space', 'SPIR': 'Space', 'IRDM': 'Space', 'GSAT': 'Space',
    // Crypto
    'COIN': 'Crypto', 'MSTR': 'Crypto', 'MARA': 'Crypto', 'RIOT': 'Crypto',
    'CLSK': 'Crypto', 'HUT': 'Crypto', 'BTDR': 'Crypto', 'BITF': 'Crypto',
    // Crypto additions
    'CORZ': 'Crypto', 'WULF': 'Crypto', 'IREN': 'Crypto', 'CIFR': 'Crypto',
    // Index Funds
    'LXU': 'Chemicals',
    'NFE': 'Energy', 'AMPY': 'Energy', 'EE': 'Energy', 'LEU': 'Energy',
    'KALU': 'Materials',
    'SPY': 'Index Fund', 'QQQ': 'Index Fund', 'IWM': 'Index Fund', 'VOO': 'Index Fund',
    'VONG': 'Index Fund', 'XMMO': 'Index Fund', 'SCHF': 'Index Fund',
    'VSS': 'Index Fund', 'SPEM': 'Index Fund', 'VOOG': 'Index Fund'
};

// Returns deduplicated list of all scan symbols (matches screenStocks() in trader.js)
function getAllSymbols() {
    const stockLists = {
        techAI: ['NVDA', 'AVGO', 'GOOGL', 'MSFT', 'META', 'ORCL', 'CRM', 'ADBE', 'NOW', 'INTU',
                 'PLTR', 'SNOW', 'AI', 'BBAI', 'SOUN', 'PATH', 'S', 'HUBS', 'ZM', 'DOCU',
                 'TEAM', 'WDAY', 'VEEV', 'ESTC', 'DDOG', 'NET', 'MDB', 'CRWD', 'PANW', 'ZS',
                 'OKTA', 'CFLT', 'GTLB', 'FROG', 'BILL', 'DOCN', 'MNDY', 'PCOR', 'APP',
                 'FTNT', 'TENB', 'QLYS', 'RPD', 'VRNS',
                 'TOST', 'GLBE', 'CART', 'GRAB', 'IOT', 'BRZE',
                 // S&P 500 Technology additions
                 'ACN', 'ADSK', 'ANET', 'CSCO', 'CTSH', 'EPAM', 'FFIV', 'FICO',
                 'GDDY', 'GEN', 'GLW', 'HPE', 'JBL', 'KEYS', 'MSI',
                 'PAYC', 'PTC', 'TEL', 'TER', 'TRMB', 'TTD', 'TYL',
                 'VRSN', 'ZBRA', 'CDW', 'AKAM', 'CIEN', 'CSGP', 'NDSN', 'TDY',
                 'GRMN', 'IT', 'CHTR',
                 // Gaming/Media
                 'EA', 'TTWO', 'FOX', 'MTCH',
                 // Mid-cap Technology
                 'CRDO', 'RMBS', 'LSCC', 'MTSI', 'DIOD', 'NTNX',
                 'ASAN', 'FIVN', 'RBRK', 'GTM', 'DT',
                 'TWLO', 'DBX', 'BOX', 'YOU', 'SMTC', 'CALX', 'PI',
                 'MANH', 'GWRE', 'WK', 'BSY', 'APPF', 'PCTY'],
        techHardware: ['AAPL', 'QCOM', 'INTC', 'MU', 'ARM', 'DELL', 'HPQ', 'AMAT', 'LRCX', 'MRVL',
                       'AMD', 'TXN', 'ADI', 'NXPI', 'KLAC', 'ASML', 'TSM', 'SNPS', 'CDNS', 'ON',
                       'MPWR', 'SWKS', 'QRVO', 'ENTG', 'FORM', 'MKSI', 'COHR', 'IPGP', 'LITE', 'AMBA',
                       'SLAB', 'CRUS', 'SYNA', 'MCHP', 'SMCI', 'WDC', 'STX', 'PSTG', 'NTAP', 'CHKP',
                       'IONQ', 'RGTI', 'QBTS', 'QUBT', 'ARQQ', 'IBM',
                       'WOLF', 'OUST', 'IMOS', 'VECO', 'POWI', 'PLXS', 'VICR'],
        evAuto: ['TSLA', 'RIVN', 'LCID', 'NIO', 'XPEV', 'LI', 'F', 'GM', 'STLA', 'TM',
                 'HMC', 'RACE', 'APTV', 'ALV', 'BLNK', 'CHPT', 'EVGO', 'PAG', 'QS',
                 'CVNA', 'KMX', 'AN', 'LAD'],
        finance: ['JPM', 'BAC', 'WFC', 'GS', 'MS', 'C', 'BLK', 'SCHW', 'V', 'MA',
                  'XYZ', 'PYPL', 'GPN', 'AXP', 'FIS', 'COF', 'ALLY', 'USB', 'PNC', 'TFC', 'RF',
                  'KEY', 'FITB', 'MTB', 'CFG', 'HBAN', 'STT', 'BK', 'NTRS',
                  'ZION', 'FHN', 'WRB', 'CB', 'TRV', 'ALL', 'PGR', 'AIG', 'MET', 'PRU',
                  'FOUR', 'PAYO', 'DLO', 'RELY', 'FLYW',
                  // S&P 500 Financial additions
                  'SPGI', 'ICE', 'CME', 'MCO', 'MSCI', 'NDAQ',
                  'AON', 'AJG', 'ACGL', 'AFL', 'CINF', 'BRO', 'GL', 'ERIE', 'EG',
                  'BRK.B', 'BX', 'KKR', 'APO', 'ARES', 'IBKR',
                  'PFG', 'L', 'BEN', 'IVZ', 'SYF', 'CBOE',
                  'RJF', 'AMP', 'TROW', 'FISV', 'HIG', 'CPAY', 'AIZ', 'JKHY',
                  'CBRE', 'FDS', 'VRSK', 'WTW', 'EFX',
                  // Mid-cap Financial
                  'WAL', 'EWBC', 'FNB', 'WTFC', 'PNFP', 'SSB', 'BOKF', 'GBCI',
                  'FLG', 'OZK', 'SBCF', 'UMBF', 'FCNCA',
                  'FNF', 'FAF', 'ESNT', 'RDN', 'KNSL', 'RLI', 'ORI', 'THG', 'AFG',
                  'RYAN', 'JEF', 'EVR', 'PJT', 'HLI', 'LPLA', 'PIPR',
                  'SF', 'MKTX', 'VIRT', 'TW'],
        growth: ['DKNG', 'RBLX', 'U', 'PINS', 'SNAP', 'SPOT', 'ABNB', 'LYFT', 'DASH', 'UBER',
                 'CPNG', 'BKNG', 'EXPE', 'TCOM', 'TRIP', 'PTON', 'LULU', 'ETSY', 'W', 'CHWY',
                 'OPEN', 'COMP', 'RKT', 'CWAN', 'DUOL', 'BROS', 'CAVA', 'HOOD', 'AFRM',
                 'UPST', 'LC', 'NU', 'SOFI', 'NFLX', 'ROKU', 'WBD', 'FOXA', 'CMCSA', 'T',
                 'SHOP', 'SE', 'BABA', 'JD', 'PDD', 'MELI'],
        healthcare: ['JNJ', 'UNH', 'LLY', 'ABBV', 'PFE', 'MRNA', 'VRTX', 'REGN', 'BMY', 'GILD',
                     'AMGN', 'CVS', 'CI', 'HUM', 'ISRG', 'TMO', 'DHR', 'ABT', 'SYK', 'BSX',
                     'MDT', 'BDX', 'BAX', 'ZBH', 'HCA', 'DVA', 'EXAS', 'ILMN',
                     'BIIB', 'ALNY', 'INCY', 'NBIX', 'UTHR', 'JAZZ', 'SRPT', 'BMRN', 'IONS', 'RGEN',
                     'CRSP', 'NTLA', 'BEAM', 'RXRX', 'TWST', 'PACB', 'EDIT', 'IOVA',
                     'PCVX', 'MDGL', 'TGTX', 'LEGN', 'DNA', 'FATE',
                     'HIMS', 'DOCS', 'OSCR',
                     'ZTS', 'WAT',
                     // S&P 500 Healthcare additions
                     'MRK', 'A', 'IQV', 'GEHC', 'HOLX', 'DXCM', 'IDXX', 'PODD', 'ALGN',
                     'EW', 'COO', 'MTD', 'WST', 'TECH', 'CNC', 'MOH', 'COR',
                     'CAH', 'MCK', 'VTRS', 'LH', 'DGX', 'RMD', 'ELV', 'STE', 'HSIC',
                     'UHS', 'CRL', 'RVTY', 'SOLV',
                     // Mid-cap Healthcare
                     'NVCR', 'GKOS', 'NVST', 'XRAY', 'TFX', 'MMSI', 'PEN', 'LNTH', 'AZTA',
                     'NEOG', 'PRCT', 'IRTC', 'HALO', 'INSM', 'RARE', 'PTCT', 'ARWR',
                     'FOLD', 'MYGN', 'GH', 'NTRA', 'SDGR', 'VERA'],
        consumer: ['AMZN', 'WMT', 'COST', 'TGT', 'HD', 'LOW', 'SBUX', 'MCD', 'CMG', 'YUM',
                   'NKE', 'RH', 'DECK', 'CROX', 'ULTA', 'ELF', 'LEVI', 'UAA', 'DIS', 'GOOG',
                   'KO', 'PEP', 'PM', 'MO', 'BUD', 'TAP', 'STZ', 'MNST', 'CELH', 'KDP',
                   'ORLY', 'AZO', 'AAP', 'GPC', 'TSCO', 'DG', 'DLTR', 'ROST', 'TJX', 'BBY',
                   'VZ', 'TMUS', 'ONON', 'BIRK', 'OMC',
                   // S&P 500 Consumer additions
                   'PG', 'CL', 'KHC', 'MDLZ', 'GIS', 'CLX', 'CHD', 'SJM', 'KMB',
                   'HRL', 'CAG', 'CPB', 'MKC', 'HSY', 'KR', 'SYY',
                   'ADM', 'TSN', 'BG', 'KVUE', 'EL', 'AMCR',
                   'DPZ', 'DRI', 'EBAY', 'HAS', 'HLT', 'LVS',
                   'MAR', 'MGM', 'NCLH', 'RCL', 'RL', 'TPR',
                   'WYNN', 'CCL', 'WSM', 'POOL', 'LW', 'NWS', 'NWSA',
                   'TKO', 'LYV', 'BF.B',
                   // Mid-cap Consumer
                   'TXRH', 'WING', 'SHAK', 'SG', 'LOCO', 'DNUT',
                   'EAT', 'CAKE', 'BJRI', 'PLAY', 'DIN', 'JACK', 'ARCO',
                   'FIVE', 'OLLI', 'BJ', 'COLM', 'VFC',
                   'GIII', 'OXM', 'PVH', 'COTY', 'MNSO',
                   'AEO', 'ANF', 'GAP', 'VSCO', 'BBWI', 'RVLV',
                   'WRBY', 'M', 'KSS', 'BURL',
                   'PENN', 'CZR', 'BYD', 'GDEN',
                   'VAC', 'MTN', 'FUN', 'PRKS'],
        energy: ['XOM', 'CVX', 'COP', 'SLB', 'EOG', 'OXY', 'MPC', 'PSX', 'VLO', 'TRGP',
                 'DVN', 'FANG', 'WMB', 'APA', 'HAL', 'BKR', 'NOV', 'FTI', 'NEE', 'DUK',
                 'SO', 'D', 'AEP', 'EXC', 'ENPH', 'SEDG', 'RUN', 'FSLR', 'PLUG',
                 'PBF', 'DK', 'CTRA', 'OVV', 'PR', 'SM', 'MGY', 'MTDR', 'CHRD', 'OKE',
                 'SMR', 'VST', 'CEG', 'CCJ', 'LNG', 'AR', 'GEV', 'VNOM', 'EQT',
                 // S&P 500 Energy/Utilities additions
                 'SRE', 'AES', 'PCG', 'EIX', 'XEL', 'WEC',
                 'ES', 'ETR', 'PEG', 'ED', 'FE', 'CNP',
                 'PPL', 'AEE', 'ATO', 'DTE', 'CMS', 'EVRG',
                 'NI', 'LNT', 'NRG', 'PNW', 'AWK', 'KMI', 'TPL', 'EXE',
                 // Mid-cap Energy/Clean Energy
                 'ARRY', 'MAXN', 'BE', 'STEM', 'SHLS',
                 'ORA', 'CWEN', 'TAC', 'CNX', 'RRC', 'WFRD',
                 'LBRT', 'PTEN', 'HP'],
        industrials: ['CAT', 'DE', 'CMI', 'EMR', 'ETN', 'PH', 'ROK', 'AME', 'DOV', 'ITW',
                      'GE', 'HON', 'MMM', 'DHI', 'LEN', 'NVR', 'PHM', 'TOL', 'BLD', 'BLDR',
                      'UNP', 'NSC', 'CSX', 'UPS', 'FDX', 'CHRW', 'JBHT', 'KNX', 'ODFL', 'XPO',
                      'CARR', 'VLTO', 'IR', 'WM', 'RSG', 'PCAR', 'PWR', 'JCI', 'AOS', 'ROP',
                      'ROCK', 'MLI', 'RUSHA', 'MYRG', 'DY', 'APOG',
                      'VRT', 'EME', 'APH', 'HUBB', 'WCC', 'TT', 'GNRC', 'GEO', 'CXW',
                      // S&P 500 Industrials additions
                      'ADP', 'OTIS', 'CTAS', 'WAB', 'FAST', 'URI', 'CPRT', 'GWW',
                      'FIX', 'ROL', 'ALLE', 'SNA', 'SWK', 'PNR', 'PAYX',
                      'DAL', 'UAL', 'LUV', 'EXPD', 'LII', 'PKG',
                      'AVY', 'MAS', 'IP', 'WY', 'BALL', 'FTV',
                      'IFF', 'BR', 'J', 'VMC', 'MLM', 'CRH', 'XYL', 'SW',
                      // Mid-cap Industrials
                      'ACM', 'MTZ', 'STRL', 'GVA', 'ROAD', 'PRIM', 'TPC', 'AGX',
                      'UFPI', 'AWI', 'TREX', 'SITE', 'BFAM', 'HRI', 'WSC',
                      'SKYW', 'ALK', 'JBLU', 'AAL',
                      'SNDR', 'SAIA', 'ARCB', 'WERN', 'HUBG', 'R', 'GATX', 'RXO',
                      'ATKR', 'AIT', 'REZI', 'LECO', 'MIDD', 'FELE', 'WTS', 'MWA', 'ESE',
                      'IEX'],
        realEstate: ['AMT', 'PLD', 'CCI', 'EQIX', 'PSA', 'DLR', 'WELL', 'O', 'VICI', 'SPG',
                     'AVB', 'EQR', 'MAA', 'UDR', 'CPT', 'ESS', 'ELS', 'SUI', 'NXRT',
                     'VTR', 'STWD', 'DOC', 'OHI', 'SBRA', 'LTC', 'HR', 'MPT', 'NHI', 'CTRE',
                     'IRM', 'CUBE', 'NSA', 'REXR', 'TRNO', 'SELF', 'SAFE',
                     // S&P 500 Real Estate additions
                     'EXR', 'ARE', 'KIM', 'REG', 'INVH', 'FRT', 'HST', 'BXP', 'SBAC',
                     // Mid-cap Real Estate
                     'GLPI', 'SLG', 'VNO', 'DEI', 'CUZ', 'HIW', 'CDP',
                     'NNN', 'ADC', 'EPRT', 'KRG', 'AKR', 'BNL', 'GTY',
                     'IIPR', 'APLE', 'RLJ', 'PEB', 'SHO', 'DRH',
                     'FR', 'STAG', 'LXP', 'COLD', 'LAMR', 'OUT'],
        materials: ['NEM', 'FCX', 'GOLD', 'AU', 'AEM', 'WPM', 'FNV', 'RGLD', 'KGC', 'HL',
                    'NUE', 'STLD', 'RS', 'CLF', 'AA', 'MT', 'TX', 'CMC', 'NB', 'ATI',
                    'DOW', 'LYB', 'EMN', 'CE', 'APD', 'LIN', 'GTLS', 'NUAI', 'ASPI', 'ECL', 'ALB', 'SQM', 'LAC',
                    'MP', 'DD', 'PPG', 'SHW', 'RPM', 'AXTA', 'FUL', 'NEU', 'USAR', 'UUUU', 'B',
                    // S&P 500 Materials additions
                    'CTVA', 'MOS', 'CF',
                    // Mid-cap Materials
                    'PAAS', 'AG', 'CDE', 'EGO', 'SSRM', 'HBM',
                    'TECK', 'RIO', 'BHP', 'VALE', 'SCCO', 'GFI', 'BTG', 'IAUX',
                    'AMR', 'HCC', 'CNR',
                    'MEOH', 'CC', 'OLN', 'TROX', 'HUN', 'WLK', 'CBT', 'NGVT',
                    'ASH', 'SON', 'SEE', 'GPK', 'SLVM'],
        defense: ['LMT', 'RTX', 'NOC', 'GD', 'BA', 'LHX', 'HII', 'TXT', 'HWM', 'AXON',
                  'KTOS', 'AVAV', 'AIR', 'SAIC', 'LDOS', 'CACI', 'BAH', 'BWXT', 'WWD', 'MOG.A',
                  'TDG', 'HEI', 'CW', 'AIN', 'PSN', 'MRCY', 'DRS',
                  'RCAT', 'JOBY', 'ACHR',
                  // Mid-cap Defense
                  'OSIS', 'VSEC', 'BDC'],
        space: ['RKLB', 'ASTS', 'LUNR', 'RDW', 'BKSY', 'SPIR', 'IRDM', 'GSAT'],
        crypto: ['COIN', 'MSTR', 'MARA', 'RIOT', 'CLSK', 'HUT', 'BTDR', 'BITF',
                 // Crypto additions
                 'CORZ', 'WULF', 'IREN', 'CIFR']
    };

    const all = [];
    for (const stocks of Object.values(stockLists)) {
        all.push(...stocks);
    }
    // Deduplicate (some stocks appear in multiple lists, e.g. GOOG in consumer + tech)
    return [...new Set(all)];
}

module.exports = { stockNames, stockSectors, getAllSymbols };
